/**
 * Generated by GitHub Copilot Agent
 * Issue: #generate-tests-for-branch-main
 * Date: 2025-12-18
 * DO NOT EDIT: This test was auto-generated. Review and modify as needed.
 */
package com.alok.payment.beneficiaries.integration;

import com.alok.payment.beneficiaries.dto.BeneficiarySearchCriteria;
import com.alok.payment.beneficiaries.dto.PagedResponse;
import com.alok.payment.beneficiaries.model.Beneficiary;
import com.alok.payment.beneficiaries.service.BeneficiaryService;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.images.PullPolicy;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest
@AutoConfigureMockMvc
@Testcontainers
@DisplayName("Beneficiary Search and Analytics Integration Tests")
class BeneficiarySearchAndAnalyticsIntegrationTest {
    
    @SuppressWarnings("resource")
    @Container
    static final PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>(
            DockerImageName.parse("ghcr.io/alokkulkarni/testcontainers-registry/testcontainers/postgres:16-alpine")
                    .asCompatibleSubstituteFor("postgres"))
            .withImagePullPolicy(PullPolicy.defaultPolicy())
            .withDatabaseName("beneficiaries_test")
            .withUsername("test")
            .withPassword("test")
            .withInitScript("init.db");
    
    @SuppressWarnings("resource")
    @Container
    static final GenericContainer<?> redis = new GenericContainer<>(
            DockerImageName.parse("ghcr.io/alokkulkarni/testcontainers-registry/testcontainers/redis:7-alpine")
                    .asCompatibleSubstituteFor("redis"))
            .withImagePullPolicy(PullPolicy.defaultPolicy())
            .withExposedPorts(6379);
    
    @DynamicPropertySource
    static void configureProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", postgres::getJdbcUrl);
        registry.add("spring.datasource.username", postgres::getUsername);
        registry.add("spring.datasource.password", postgres::getPassword);
        registry.add("spring.data.redis.host", redis::getHost);
        registry.add("spring.data.redis.port", redis::getFirstMappedPort);
    }
    
    @Autowired
    private MockMvc mockMvc;
    
    @Autowired
    private ObjectMapper objectMapper;
    
    @Autowired
    private BeneficiaryService beneficiaryService;
    
    // ===== Search Functionality Tests =====
    
    @Test
    @DisplayName("Should search beneficiaries by customer ID")
    void shouldSearchBeneficiariesByCustomerId() {
        // Given
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId("CUST001");
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(criteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).isNotEmpty();
        assertThat(result.getContent()).allMatch(b -> "CUST001".equals(b.getCustomerId()));
        assertThat(result.getTotalElements()).isGreaterThan(0);
        assertThat(result.getPage()).isEqualTo(0);
        assertThat(result.isFirst()).isTrue();
    }
    
    @Test
    @DisplayName("Should search beneficiaries with name filter")
    void shouldSearchBeneficiariesWithNameFilter() {
        // Given
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId("CUST001");
        criteria.setBeneficiaryName("Old");
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(criteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).isNotEmpty();
        assertThat(result.getContent()).allMatch(b -> 
                b.getBeneficiaryName().toLowerCase().contains("old"));
    }
    
    @Test
    @DisplayName("Should search beneficiaries with type filter")
    void shouldSearchBeneficiariesWithTypeFilter() {
        // Given
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setBeneficiaryType("DOMESTIC");
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(criteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).isNotEmpty();
        assertThat(result.getContent()).allMatch(b -> "DOMESTIC".equals(b.getBeneficiaryType()));
    }
    
    @Test
    @DisplayName("Should search beneficiaries with status filter")
    void shouldSearchBeneficiariesWithStatusFilter() {
        // Given
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setStatus("ACTIVE");
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(criteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).isNotEmpty();
        assertThat(result.getContent()).allMatch(b -> "ACTIVE".equals(b.getStatus()));
    }
    
    @Test
    @DisplayName("Should search beneficiaries with pagination")
    void shouldSearchBeneficiariesWithPagination() {
        // Given - First page
        BeneficiarySearchCriteria criteria1 = new BeneficiarySearchCriteria();
        criteria1.setCustomerId("CUST002"); // Has 3 beneficiaries
        criteria1.setPage(0);
        criteria1.setSize(2);
        
        // When
        PagedResponse<Beneficiary> page1 = beneficiaryService.searchBeneficiaries(criteria1);
        
        // Then
        assertThat(page1).isNotNull();
        assertThat(page1.getContent()).hasSize(2);
        assertThat(page1.getPage()).isEqualTo(0);
        assertThat(page1.getTotalPages()).isEqualTo(2);
        assertThat(page1.isFirst()).isTrue();
        assertThat(page1.isLast()).isFalse();
        
        // Given - Second page
        BeneficiarySearchCriteria criteria2 = new BeneficiarySearchCriteria();
        criteria2.setCustomerId("CUST002");
        criteria2.setPage(1);
        criteria2.setSize(2);
        
        // When
        PagedResponse<Beneficiary> page2 = beneficiaryService.searchBeneficiaries(criteria2);
        
        // Then
        assertThat(page2).isNotNull();
        assertThat(page2.getContent()).hasSize(1);
        assertThat(page2.getPage()).isEqualTo(1);
        assertThat(page2.isFirst()).isFalse();
        assertThat(page2.isLast()).isTrue();
    }
    
    @Test
    @DisplayName("Should search beneficiaries with sorting by name")
    void shouldSearchBeneficiariesWithSortingByName() {
        // Given
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId("CUST002");
        criteria.setSortBy("beneficiaryName");
        criteria.setSortDirection("ASC");
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(criteria);
        
        // Then
        assertThat(result).isNotNull();
        List<Beneficiary> beneficiaries = result.getContent();
        for (int i = 1; i < beneficiaries.size(); i++) {
            String prev = beneficiaries.get(i - 1).getBeneficiaryName();
            String curr = beneficiaries.get(i).getBeneficiaryName();
            assertThat(prev.compareTo(curr)).isLessThanOrEqualTo(0);
        }
    }
    
    @Test
    @DisplayName("Should search beneficiaries with date range filter")
    void shouldSearchBeneficiariesWithDateRangeFilter() {
        // Given
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCreatedAfter(LocalDateTime.now().minusYears(1));
        criteria.setCreatedBefore(LocalDateTime.now().plusDays(1));
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(criteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).isNotEmpty();
    }
    
    @Test
    @DisplayName("Should return empty results when no beneficiaries match criteria")
    void shouldReturnEmptyResultsWhenNoBeneficiariesMatchCriteria() {
        // Given
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId("NONEXISTENT_CUSTOMER");
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(criteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).isEmpty();
        assertThat(result.getTotalElements()).isEqualTo(0);
        assertThat(result.getTotalPages()).isEqualTo(0);
    }
    
    // ===== Analytics Functionality Tests =====
    
    @Test
    @DisplayName("Should get customer beneficiary analytics")
    void shouldGetCustomerBeneficiaryAnalytics() {
        // When
        Map<String, Object> analytics = beneficiaryService.getCustomerBeneficiaryAnalytics("CUST001");
        
        // Then
        assertThat(analytics).isNotNull();
        assertThat(analytics).containsKeys(
                "customerId", 
                "totalBeneficiaries", 
                "activeBeneficiaries", 
                "inactiveBeneficiaries",
                "beneficiariesByType",
                "beneficiariesByBank"
        );
        assertThat(analytics.get("customerId")).isEqualTo("CUST001");
        assertThat((Integer) analytics.get("totalBeneficiaries")).isGreaterThan(0);
    }
    
    @Test
    @DisplayName("Should get analytics with type breakdown")
    void shouldGetAnalyticsWithTypeBreakdown() {
        // When
        Map<String, Object> analytics = beneficiaryService.getCustomerBeneficiaryAnalytics("CUST002");
        
        // Then
        assertThat(analytics).isNotNull();
        @SuppressWarnings("unchecked")
        Map<String, Long> byType = (Map<String, Long>) analytics.get("beneficiariesByType");
        assertThat(byType).isNotNull();
        assertThat(byType.values().stream().mapToLong(Long::longValue).sum()).isGreaterThan(0);
    }
    
    @Test
    @DisplayName("Should get analytics with bank breakdown")
    void shouldGetAnalyticsWithBankBreakdown() {
        // When
        Map<String, Object> analytics = beneficiaryService.getCustomerBeneficiaryAnalytics("CUST002");
        
        // Then
        assertThat(analytics).isNotNull();
        @SuppressWarnings("unchecked")
        Map<String, Long> byBank = (Map<String, Long>) analytics.get("beneficiariesByBank");
        assertThat(byBank).isNotNull();
    }
    
    @Test
    @DisplayName("Should find potential duplicate beneficiaries")
    void shouldFindPotentialDuplicateBeneficiaries() {
        // When
        List<Map<String, Object>> duplicates = beneficiaryService.findPotentialDuplicates("CUST001");
        
        // Then
        assertThat(duplicates).isNotNull();
        // Note: May be empty if no duplicates exist in test data
    }
    
    @Test
    @DisplayName("Should get beneficiary usage report")
    void shouldGetBeneficiaryUsageReport() {
        // Given
        LocalDateTime startDate = LocalDateTime.now().minusMonths(1);
        LocalDateTime endDate = LocalDateTime.now().plusDays(1);
        
        // When
        Map<String, Object> report = beneficiaryService.getBeneficiaryUsageReport(
                "CUST001", startDate, endDate);
        
        // Then
        assertThat(report).isNotNull();
        assertThat(report).containsKeys(
                "customerId",
                "reportPeriodStart",
                "reportPeriodEnd",
                "totalBeneficiaries",
                "beneficiariesAddedInPeriod",
                "growthRatePercent"
        );
        assertThat(report.get("customerId")).isEqualTo("CUST001");
        assertThat((Integer) report.get("totalBeneficiaries")).isGreaterThanOrEqualTo(0);
    }
    
    @Test
    @DisplayName("Should get usage report with growth rate")
    void shouldGetUsageReportWithGrowthRate() {
        // Given
        LocalDateTime startDate = LocalDateTime.now().minusYears(1);
        LocalDateTime endDate = LocalDateTime.now().plusDays(1);
        
        // When
        Map<String, Object> report = beneficiaryService.getBeneficiaryUsageReport(
                "CUST002", startDate, endDate);
        
        // Then
        assertThat(report).isNotNull();
        assertThat(report.get("growthRatePercent")).isNotNull();
        Double growthRate = (Double) report.get("growthRatePercent");
        assertThat(growthRate).isGreaterThanOrEqualTo(0.0);
    }
    
    @Test
    @DisplayName("Should handle empty customer in analytics")
    void shouldHandleEmptyCustomerInAnalytics() {
        // When
        Map<String, Object> analytics = beneficiaryService.getCustomerBeneficiaryAnalytics("CUST_NO_DATA");
        
        // Then
        assertThat(analytics).isNotNull();
        assertThat(analytics.get("customerId")).isEqualTo("CUST_NO_DATA");
        assertThat((Integer) analytics.get("totalBeneficiaries")).isEqualTo(0);
        assertThat((Long) analytics.get("activeBeneficiaries")).isEqualTo(0L);
    }
    
    @Test
    @DisplayName("Should handle empty customer in duplicates search")
    void shouldHandleEmptyCustomerInDuplicatesSearch() {
        // When
        List<Map<String, Object>> duplicates = beneficiaryService.findPotentialDuplicates("CUST_NO_DATA");
        
        // Then
        assertThat(duplicates).isNotNull();
        assertThat(duplicates).isEmpty();
    }
    
    @Test
    @DisplayName("Should handle empty customer in usage report")
    void shouldHandleEmptyCustomerInUsageReport() {
        // Given
        LocalDateTime startDate = LocalDateTime.now().minusMonths(1);
        LocalDateTime endDate = LocalDateTime.now().plusDays(1);
        
        // When
        Map<String, Object> report = beneficiaryService.getBeneficiaryUsageReport(
                "CUST_NO_DATA", startDate, endDate);
        
        // Then
        assertThat(report).isNotNull();
        assertThat(report.get("customerId")).isEqualTo("CUST_NO_DATA");
        assertThat((Integer) report.get("totalBeneficiaries")).isEqualTo(0);
        assertThat((Integer) report.get("beneficiariesAddedInPeriod")).isEqualTo(0);
    }
    
    @Test
    @DisplayName("Should search beneficiaries with multiple criteria")
    void shouldSearchBeneficiariesWithMultipleCriteria() {
        // Given
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId("CUST003");
        criteria.setBeneficiaryType("DOMESTIC");
        criteria.setStatus("ACTIVE");
        criteria.setPage(0);
        criteria.setSize(10);
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(criteria);
        
        // Then
        assertThat(result).isNotNull();
        if (!result.getContent().isEmpty()) {
            assertThat(result.getContent()).allMatch(b -> 
                    "CUST003".equals(b.getCustomerId()) &&
                    "DOMESTIC".equals(b.getBeneficiaryType()) &&
                    "ACTIVE".equals(b.getStatus())
            );
        }
    }
    
    @Test
    @DisplayName("Should get analytics for customer with multiple beneficiary types")
    void shouldGetAnalyticsForCustomerWithMultipleBeneficiaryTypes() {
        // When
        Map<String, Object> analytics = beneficiaryService.getCustomerBeneficiaryAnalytics("CUST003");
        
        // Then
        assertThat(analytics).isNotNull();
        @SuppressWarnings("unchecked")
        Map<String, Long> byType = (Map<String, Long>) analytics.get("beneficiariesByType");
        assertThat(byType).isNotNull();
    }
}
