/**
 * Generated by GitHub Copilot Agent
 * Issue: #generate-tests-for-branch-main
 * Date: 2025-12-18
 * DO NOT EDIT: This test was auto-generated. Review and modify as needed.
 */
package com.alok.payment.beneficiaries.unit.repository;

import com.alok.payment.beneficiaries.model.Beneficiary;
import com.alok.payment.beneficiaries.repository.BeneficiaryRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.data.jdbc.DataJdbcTest;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.images.PullPolicy;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

@DataJdbcTest
@Testcontainers
@DisplayName("BeneficiaryRepository Unit Tests")
class BeneficiaryRepositoryTest {

    @SuppressWarnings("resource")
    @Container
    static final PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>(
            DockerImageName.parse("ghcr.io/alokkulkarni/testcontainers-registry/testcontainers/postgres:16-alpine")
                    .asCompatibleSubstituteFor("postgres"))
            .withImagePullPolicy(PullPolicy.defaultPolicy())
            .withDatabaseName("beneficiaries_test")
            .withUsername("test")
            .withPassword("test")
            .withInitScript("init.db");

    @DynamicPropertySource
    static void configureProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", postgres::getJdbcUrl);
        registry.add("spring.datasource.username", postgres::getUsername);
        registry.add("spring.datasource.password", postgres::getPassword);
    }

    @Autowired
    private BeneficiaryRepository beneficiaryRepository;

    private Beneficiary testBeneficiary;

    @BeforeEach
    void setUp() {
        testBeneficiary = new Beneficiary();
        testBeneficiary.setCustomerId("TEST_CUST");
        testBeneficiary.setAccountNumber("TEST_ACC");
        testBeneficiary.setBeneficiaryName("Test Beneficiary");
        testBeneficiary.setBeneficiaryAccountNumber("TEST_BEN_ACC");
        testBeneficiary.setBeneficiaryBankCode("TEST_BANK");
        testBeneficiary.setBeneficiaryBankName("Test Bank Name");
        testBeneficiary.setBeneficiaryType("DOMESTIC");
        testBeneficiary.setStatus("ACTIVE");
        testBeneficiary.setCreatedAt(LocalDateTime.now());
        testBeneficiary.setUpdatedAt(LocalDateTime.now());
    }

    @Test
    @DisplayName("Should find beneficiaries by customer ID")
    void shouldFindBeneficiariesByCustomerId() {
        // Given - CUST001 has beneficiaries in init.db
        
        // When
        List<Beneficiary> result = beneficiaryRepository.findByCustomerId("CUST001");
        
        // Then
        assertThat(result).isNotNull().isNotEmpty();
        assertThat(result).allMatch(b -> "CUST001".equals(b.getCustomerId()));
        assertThat(result).allMatch(b -> "ACTIVE".equals(b.getStatus()));
    }

    @Test
    @DisplayName("Should find beneficiaries by customer ID and account number")
    void shouldFindBeneficiariesByCustomerIdAndAccountNumber() {
        // Given - CUST003 has multiple accounts in init.db
        
        // When
        List<Beneficiary> result = beneficiaryRepository.findByCustomerIdAndAccountNumber("CUST003", "ACC_A");
        
        // Then
        assertThat(result).isNotNull().isNotEmpty();
        assertThat(result).allMatch(b -> "CUST003".equals(b.getCustomerId()));
        assertThat(result).allMatch(b -> "ACC_A".equals(b.getAccountNumber()));
        assertThat(result).allMatch(b -> "ACTIVE".equals(b.getStatus()));
    }

    @Test
    @DisplayName("Should find beneficiary by ID and customer ID")
    void shouldFindBeneficiaryByIdAndCustomerId() {
        // Given - ID 1 belongs to CUST001 in init.db
        
        // When
        Optional<Beneficiary> result = beneficiaryRepository.findByIdAndCustomerId(1L, "CUST001");
        
        // Then
        assertThat(result).isPresent();
        assertThat(result.get().getId()).isEqualTo(1L);
        assertThat(result.get().getCustomerId()).isEqualTo("CUST001");
        assertThat(result.get().getStatus()).isEqualTo("ACTIVE");
    }

    @Test
    @DisplayName("Should not find beneficiary with wrong customer ID")
    void shouldNotFindBeneficiaryWithWrongCustomerId() {
        // Given - ID 1 belongs to CUST001, not CUST999
        
        // When
        Optional<Beneficiary> result = beneficiaryRepository.findByIdAndCustomerId(1L, "CUST999");
        
        // Then
        assertThat(result).isEmpty();
    }

    @Test
    @DisplayName("Should find beneficiary by customer ID and beneficiary account number")
    void shouldFindBeneficiaryByCustomerIdAndBeneficiaryAccountNumber() {
        // Given - CUST001 has beneficiary with account 12345678 in init.db
        
        // When
        Optional<Beneficiary> result = beneficiaryRepository
                .findByCustomerIdAndBeneficiaryAccountNumber("CUST001", "12345678");
        
        // Then
        assertThat(result).isPresent();
        assertThat(result.get().getCustomerId()).isEqualTo("CUST001");
        assertThat(result.get().getBeneficiaryAccountNumber()).isEqualTo("12345678");
        assertThat(result.get().getStatus()).isEqualTo("ACTIVE");
    }

    @Test
    @DisplayName("Should soft delete beneficiary by ID and customer ID")
    void shouldSoftDeleteBeneficiaryByIdAndCustomerId() {
        // Given - Create and save a test beneficiary
        Beneficiary saved = beneficiaryRepository.save(testBeneficiary);
        
        // When
        int deleted = beneficiaryRepository.softDeleteByIdAndCustomerId(saved.getId(), "TEST_CUST");
        
        // Then
        assertThat(deleted).isEqualTo(1);
        
        // Verify it's soft deleted (status changed to DELETED)
        Optional<Beneficiary> result = beneficiaryRepository.findByIdAndCustomerId(saved.getId(), "TEST_CUST");
        assertThat(result).isEmpty(); // Should not be found as active
    }

    @Test
    @DisplayName("Should return 0 when soft deleting non-existent beneficiary")
    void shouldReturn0WhenSoftDeletingNonExistentBeneficiary() {
        // When
        int deleted = beneficiaryRepository.softDeleteByIdAndCustomerId(99999L, "CUST999");
        
        // Then
        assertThat(deleted).isEqualTo(0);
    }

    @Test
    @DisplayName("Should search beneficiaries with customer ID filter")
    void shouldSearchBeneficiariesWithCustomerIdFilter() {
        // When
        List<Beneficiary> result = beneficiaryRepository.searchBeneficiaries(
                "CUST001",    // customerId
                null,         // beneficiaryName
                null,         // beneficiaryType
                null,         // status
                null,         // beneficiaryBankCode
                null,         // createdAfter
                null,         // createdBefore
                "createdAt",  // sortBy
                "DESC",       // sortDirection
                10,           // limit
                0             // offset
        );
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result).allMatch(b -> "CUST001".equals(b.getCustomerId()));
    }

    @Test
    @DisplayName("Should search beneficiaries with name filter")
    void shouldSearchBeneficiariesWithNameFilter() {
        // When - Search for beneficiary name containing "Old"
        List<Beneficiary> result = beneficiaryRepository.searchBeneficiaries(
                "CUST001",    // customerId
                "Old",        // beneficiaryName (partial match)
                null,         // beneficiaryType
                null,         // status
                null,         // beneficiaryBankCode
                null,         // createdAfter
                null,         // createdBefore
                "createdAt",  // sortBy
                "DESC",       // sortDirection
                10,           // limit
                0             // offset
        );
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result).allMatch(b -> b.getBeneficiaryName().toLowerCase().contains("old"));
    }

    @Test
    @DisplayName("Should search beneficiaries with type filter")
    void shouldSearchBeneficiariesWithTypeFilter() {
        // When
        List<Beneficiary> result = beneficiaryRepository.searchBeneficiaries(
                null,            // customerId
                null,            // beneficiaryName
                "DOMESTIC",      // beneficiaryType
                null,            // status
                null,            // beneficiaryBankCode
                null,            // createdAfter
                null,            // createdBefore
                "createdAt",     // sortBy
                "DESC",          // sortDirection
                10,              // limit
                0                // offset
        );
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result).allMatch(b -> "DOMESTIC".equals(b.getBeneficiaryType()));
    }

    @Test
    @DisplayName("Should search beneficiaries with status filter")
    void shouldSearchBeneficiariesWithStatusFilter() {
        // When
        List<Beneficiary> result = beneficiaryRepository.searchBeneficiaries(
                null,         // customerId
                null,         // beneficiaryName
                null,         // beneficiaryType
                "ACTIVE",     // status
                null,         // beneficiaryBankCode
                null,         // createdAfter
                null,         // createdBefore
                "createdAt",  // sortBy
                "DESC",       // sortDirection
                100,          // limit
                0             // offset
        );
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result).allMatch(b -> "ACTIVE".equals(b.getStatus()));
    }

    @Test
    @DisplayName("Should search beneficiaries with bank code filter")
    void shouldSearchBeneficiariesWithBankCodeFilter() {
        // When
        List<Beneficiary> result = beneficiaryRepository.searchBeneficiaries(
                null,          // customerId
                null,          // beneficiaryName
                null,          // beneficiaryType
                null,          // status
                "BANKCODE1",   // beneficiaryBankCode
                null,          // createdAfter
                null,          // createdBefore
                "createdAt",   // sortBy
                "DESC",        // sortDirection
                10,            // limit
                0              // offset
        );
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result).allMatch(b -> "BANKCODE1".equals(b.getBeneficiaryBankCode()));
    }

    @Test
    @DisplayName("Should search beneficiaries with date range filter")
    void shouldSearchBeneficiariesWithDateRangeFilter() {
        // Given
        LocalDateTime oneYearAgo = LocalDateTime.now().minusYears(1);
        LocalDateTime tomorrow = LocalDateTime.now().plusDays(1);
        
        // When
        List<Beneficiary> result = beneficiaryRepository.searchBeneficiaries(
                null,         // customerId
                null,         // beneficiaryName
                null,         // beneficiaryType
                null,         // status
                null,         // beneficiaryBankCode
                oneYearAgo,   // createdAfter
                tomorrow,     // createdBefore
                "createdAt",  // sortBy
                "DESC",       // sortDirection
                100,          // limit
                0             // offset
        );
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result).allMatch(b -> 
                b.getCreatedAt().isAfter(oneYearAgo) && b.getCreatedAt().isBefore(tomorrow));
    }

    @Test
    @DisplayName("Should search beneficiaries with pagination")
    void shouldSearchBeneficiariesWithPagination() {
        // When - Get first page
        List<Beneficiary> page1 = beneficiaryRepository.searchBeneficiaries(
                "CUST002",    // customerId - has 3 beneficiaries
                null,         // beneficiaryName
                null,         // beneficiaryType
                null,         // status
                null,         // beneficiaryBankCode
                null,         // createdAfter
                null,         // createdBefore
                "createdAt",  // sortBy
                "DESC",       // sortDirection
                2,            // limit - 2 per page
                0             // offset - first page
        );
        
        // Then
        assertThat(page1).hasSize(2);
        
        // When - Get second page
        List<Beneficiary> page2 = beneficiaryRepository.searchBeneficiaries(
                "CUST002",    // customerId
                null,         // beneficiaryName
                null,         // beneficiaryType
                null,         // status
                null,         // beneficiaryBankCode
                null,         // createdAfter
                null,         // createdBefore
                "createdAt",  // sortBy
                "DESC",       // sortDirection
                2,            // limit - 2 per page
                2             // offset - second page
        );
        
        // Then
        assertThat(page2).hasSize(1); // Only 1 left on second page
    }

    @Test
    @DisplayName("Should search beneficiaries sorted by name ascending")
    void shouldSearchBeneficiariesSortedByNameAscending() {
        // When
        List<Beneficiary> result = beneficiaryRepository.searchBeneficiaries(
                "CUST002",           // customerId
                null,                // beneficiaryName
                null,                // beneficiaryType
                null,                // status
                null,                // beneficiaryBankCode
                null,                // createdAfter
                null,                // createdBefore
                "beneficiaryName",   // sortBy
                "ASC",               // sortDirection
                10,                  // limit
                0                    // offset
        );
        
        // Then
        assertThat(result).isNotNull();
        // Verify ascending order
        for (int i = 1; i < result.size(); i++) {
            String prev = result.get(i - 1).getBeneficiaryName();
            String curr = result.get(i).getBeneficiaryName();
            assertThat(prev.compareTo(curr)).isLessThanOrEqualTo(0);
        }
    }

    @Test
    @DisplayName("Should search beneficiaries sorted by name descending")
    void shouldSearchBeneficiariesSortedByNameDescending() {
        // When
        List<Beneficiary> result = beneficiaryRepository.searchBeneficiaries(
                "CUST002",           // customerId
                null,                // beneficiaryName
                null,                // beneficiaryType
                null,                // status
                null,                // beneficiaryBankCode
                null,                // createdAfter
                null,                // createdBefore
                "beneficiaryName",   // sortBy
                "DESC",              // sortDirection
                10,                  // limit
                0                    // offset
        );
        
        // Then
        assertThat(result).isNotNull();
        // Verify descending order
        for (int i = 1; i < result.size(); i++) {
            String prev = result.get(i - 1).getBeneficiaryName();
            String curr = result.get(i).getBeneficiaryName();
            assertThat(prev.compareTo(curr)).isGreaterThanOrEqualTo(0);
        }
    }

    @Test
    @DisplayName("Should count beneficiaries with filters")
    void shouldCountBeneficiariesWithFilters() {
        // When
        long count = beneficiaryRepository.countBeneficiaries(
                "CUST001",    // customerId
                null,         // beneficiaryName
                null,         // beneficiaryType
                null,         // status
                null,         // beneficiaryBankCode
                null,         // createdAfter
                null          // createdBefore
        );
        
        // Then
        assertThat(count).isGreaterThan(0);
    }

    @Test
    @DisplayName("Should count all active beneficiaries when no filters provided")
    void shouldCountAllActiveBeneficiariesWhenNoFiltersProvided() {
        // When
        long count = beneficiaryRepository.countBeneficiaries(
                null,    // customerId
                null,    // beneficiaryName
                null,    // beneficiaryType
                null,    // status - all statuses
                null,    // beneficiaryBankCode
                null,    // createdAfter
                null     // createdBefore
        );
        
        // Then
        assertThat(count).isGreaterThan(0);
    }

    @Test
    @DisplayName("Should count beneficiaries with multiple filters")
    void shouldCountBeneficiariesWithMultipleFilters() {
        // When
        long count = beneficiaryRepository.countBeneficiaries(
                "CUST001",       // customerId
                null,            // beneficiaryName
                "DOMESTIC",      // beneficiaryType
                "ACTIVE",        // status
                null,            // beneficiaryBankCode
                null,            // createdAfter
                null             // createdBefore
        );
        
        // Then
        assertThat(count).isGreaterThanOrEqualTo(0);
    }

    @Test
    @DisplayName("Should return empty list when no beneficiaries match search criteria")
    void shouldReturnEmptyListWhenNoBeneficiariesMatchSearchCriteria() {
        // When
        List<Beneficiary> result = beneficiaryRepository.searchBeneficiaries(
                "NONEXISTENT_CUSTOMER",  // customerId that doesn't exist
                null,                     // beneficiaryName
                null,                     // beneficiaryType
                null,                     // status
                null,                     // beneficiaryBankCode
                null,                     // createdAfter
                null,                     // createdBefore
                "createdAt",              // sortBy
                "DESC",                   // sortDirection
                10,                       // limit
                0                         // offset
        );
        
        // Then
        assertThat(result).isEmpty();
    }

    @Test
    @DisplayName("Should count zero when no beneficiaries match criteria")
    void shouldCountZeroWhenNoBeneficiariesMatchCriteria() {
        // When
        long count = beneficiaryRepository.countBeneficiaries(
                "NONEXISTENT_CUSTOMER",  // customerId that doesn't exist
                null,                     // beneficiaryName
                null,                     // beneficiaryType
                null,                     // status
                null,                     // beneficiaryBankCode
                null,                     // createdAfter
                null                      // createdBefore
        );
        
        // Then
        assertThat(count).isEqualTo(0);
    }
}
