/**
 * Generated by GitHub Copilot Agent
 * Issue: #0
 * Date: 2025-12-18
 * DO NOT EDIT: This test was auto-generated. Review and modify as needed.
 */
package com.alok.payment.beneficiaries.unit.repository;

import com.alok.payment.beneficiaries.model.Beneficiary;
import com.alok.payment.beneficiaries.repository.BeneficiaryRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.data.jdbc.DataJdbcTest;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.images.PullPolicy;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

@DataJdbcTest
@Testcontainers
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@DisplayName("BeneficiaryRepository Unit Tests")
class BeneficiaryRepositoryTest {

    @SuppressWarnings("resource")
    @Container
    static final PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>(
            DockerImageName.parse("ghcr.io/alokkulkarni/testcontainers-registry/testcontainers/postgres:16-alpine").asCompatibleSubstituteFor("postgres"))
            .withImagePullPolicy(PullPolicy.defaultPolicy())
            .withDatabaseName("beneficiaries_test")
            .withUsername("test")
            .withPassword("test")
            .withInitScript("init.db");

    @DynamicPropertySource
    static void configureProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", postgres::getJdbcUrl);
        registry.add("spring.datasource.username", postgres::getUsername);
        registry.add("spring.datasource.password", postgres::getPassword);
    }

    @Autowired
    private BeneficiaryRepository beneficiaryRepository;

    private Beneficiary testBeneficiary;

    @BeforeEach
    void setUp() {
        testBeneficiary = new Beneficiary();
        testBeneficiary.setCustomerId("TEST_CUST_001");
        testBeneficiary.setAccountNumber("TEST_ACC_001");
        testBeneficiary.setBeneficiaryName("Test Beneficiary");
        testBeneficiary.setBeneficiaryAccountNumber("TEST_BEN_001");
        testBeneficiary.setBeneficiaryBankCode("TEST_BANK_001");
        testBeneficiary.setBeneficiaryBankName("Test Bank");
        testBeneficiary.setBeneficiaryType("DOMESTIC");
        testBeneficiary.setStatus("ACTIVE");
        testBeneficiary.setCreatedAt(LocalDateTime.now());
        testBeneficiary.setUpdatedAt(LocalDateTime.now());
    }

    @Test
    @DisplayName("Should find beneficiaries by customer ID")
    void shouldFindBeneficiariesByCustomerId() {
        // Given
        Beneficiary saved = beneficiaryRepository.save(testBeneficiary);

        // When
        List<Beneficiary> result = beneficiaryRepository.findByCustomerId("TEST_CUST_001");

        // Then
        assertThat(result).isNotEmpty();
        assertThat(result).anyMatch(b -> b.getId().equals(saved.getId()));
        assertThat(result).allMatch(b -> "ACTIVE".equals(b.getStatus()));
    }

    @Test
    @DisplayName("Should find beneficiaries by customer ID and account number")
    void shouldFindBeneficiariesByCustomerIdAndAccountNumber() {
        // Given
        beneficiaryRepository.save(testBeneficiary);

        // When
        List<Beneficiary> result = beneficiaryRepository.findByCustomerIdAndAccountNumber(
                "TEST_CUST_001", "TEST_ACC_001");

        // Then
        assertThat(result).isNotEmpty();
        assertThat(result).allMatch(b -> "TEST_CUST_001".equals(b.getCustomerId()));
        assertThat(result).allMatch(b -> "TEST_ACC_001".equals(b.getAccountNumber()));
        assertThat(result).allMatch(b -> "ACTIVE".equals(b.getStatus()));
    }

    @Test
    @DisplayName("Should find beneficiaries when account number is null")
    void shouldFindBeneficiariesWhenAccountNumberIsNull() {
        // Given
        beneficiaryRepository.save(testBeneficiary);

        // When
        List<Beneficiary> result = beneficiaryRepository.findByCustomerIdAndAccountNumber(
                "TEST_CUST_001", null);

        // Then
        assertThat(result).isNotEmpty();
        assertThat(result).allMatch(b -> "TEST_CUST_001".equals(b.getCustomerId()));
    }

    @Test
    @DisplayName("Should find beneficiary by ID and customer ID")
    void shouldFindBeneficiaryByIdAndCustomerId() {
        // Given
        Beneficiary saved = beneficiaryRepository.save(testBeneficiary);

        // When
        Optional<Beneficiary> result = beneficiaryRepository.findByIdAndCustomerId(
                saved.getId(), "TEST_CUST_001");

        // Then
        assertThat(result).isPresent();
        assertThat(result.get().getId()).isEqualTo(saved.getId());
        assertThat(result.get().getCustomerId()).isEqualTo("TEST_CUST_001");
        assertThat(result.get().getStatus()).isEqualTo("ACTIVE");
    }

    @Test
    @DisplayName("Should not find beneficiary with wrong customer ID")
    void shouldNotFindBeneficiaryWithWrongCustomerId() {
        // Given
        Beneficiary saved = beneficiaryRepository.save(testBeneficiary);

        // When
        Optional<Beneficiary> result = beneficiaryRepository.findByIdAndCustomerId(
                saved.getId(), "WRONG_CUSTOMER");

        // Then
        assertThat(result).isEmpty();
    }

    @Test
    @DisplayName("Should find beneficiary by customer ID and beneficiary account number")
    void shouldFindBeneficiaryByCustomerIdAndBeneficiaryAccountNumber() {
        // Given
        beneficiaryRepository.save(testBeneficiary);

        // When
        Optional<Beneficiary> result = beneficiaryRepository.findByCustomerIdAndBeneficiaryAccountNumber(
                "TEST_CUST_001", "TEST_BEN_001");

        // Then
        assertThat(result).isPresent();
        assertThat(result.get().getCustomerId()).isEqualTo("TEST_CUST_001");
        assertThat(result.get().getBeneficiaryAccountNumber()).isEqualTo("TEST_BEN_001");
        assertThat(result.get().getStatus()).isEqualTo("ACTIVE");
    }

    @Test
    @DisplayName("Should soft delete beneficiary by ID and customer ID")
    void shouldSoftDeleteBeneficiaryByIdAndCustomerId() {
        // Given
        Beneficiary saved = beneficiaryRepository.save(testBeneficiary);

        // When
        int result = beneficiaryRepository.softDeleteByIdAndCustomerId(saved.getId(), "TEST_CUST_001");

        // Then
        assertThat(result).isEqualTo(1);
        
        // Verify beneficiary is not found in active search
        Optional<Beneficiary> found = beneficiaryRepository.findByIdAndCustomerId(saved.getId(), "TEST_CUST_001");
        assertThat(found).isEmpty();
    }

    @Test
    @DisplayName("Should return 0 when soft deleting non-existent beneficiary")
    void shouldReturn0WhenSoftDeletingNonExistentBeneficiary() {
        // When
        int result = beneficiaryRepository.softDeleteByIdAndCustomerId(999L, "TEST_CUST_001");

        // Then
        assertThat(result).isEqualTo(0);
    }

    @Test
    @DisplayName("Should search beneficiaries with all filters")
    void shouldSearchBeneficiariesWithAllFilters() {
        // Given
        testBeneficiary.setBeneficiaryType("INTERNATIONAL");
        beneficiaryRepository.save(testBeneficiary);

        // When
        List<Beneficiary> result = beneficiaryRepository.searchBeneficiaries(
                "TEST_CUST_001",
                "Test",
                "INTERNATIONAL",
                "ACTIVE",
                "TEST_BANK_001",
                LocalDateTime.now().minusDays(1),
                LocalDateTime.now().plusDays(1),
                "createdAt",
                "DESC",
                10,
                0
        );

        // Then
        assertThat(result).isNotEmpty();
        assertThat(result).allMatch(b -> b.getCustomerId().equals("TEST_CUST_001"));
        assertThat(result).allMatch(b -> b.getBeneficiaryName().contains("Test"));
        assertThat(result).allMatch(b -> b.getBeneficiaryType().equals("INTERNATIONAL"));
        assertThat(result).allMatch(b -> b.getStatus().equals("ACTIVE"));
    }

    @Test
    @DisplayName("Should search beneficiaries with null filters")
    void shouldSearchBeneficiariesWithNullFilters() {
        // Given
        beneficiaryRepository.save(testBeneficiary);

        // When
        List<Beneficiary> result = beneficiaryRepository.searchBeneficiaries(
                null, null, null, null, null, null, null,
                "createdAt", "DESC", 10, 0
        );

        // Then
        assertThat(result).isNotEmpty();
    }

    @Test
    @DisplayName("Should search beneficiaries sorted by name ascending")
    void shouldSearchBeneficiariesSortedByNameAscending() {
        // Given
        Beneficiary b1 = new Beneficiary();
        b1.setCustomerId("TEST_CUST_002");
        b1.setAccountNumber("TEST_ACC_002");
        b1.setBeneficiaryName("Alice");
        b1.setBeneficiaryAccountNumber("BEN_002");
        b1.setBeneficiaryBankCode("BANK_002");
        b1.setBeneficiaryBankName("Bank 2");
        b1.setBeneficiaryType("DOMESTIC");
        b1.setStatus("ACTIVE");
        b1.setCreatedAt(LocalDateTime.now());
        b1.setUpdatedAt(LocalDateTime.now());
        
        Beneficiary b2 = new Beneficiary();
        b2.setCustomerId("TEST_CUST_002");
        b2.setAccountNumber("TEST_ACC_002");
        b2.setBeneficiaryName("Zara");
        b2.setBeneficiaryAccountNumber("BEN_003");
        b2.setBeneficiaryBankCode("BANK_002");
        b2.setBeneficiaryBankName("Bank 2");
        b2.setBeneficiaryType("DOMESTIC");
        b2.setStatus("ACTIVE");
        b2.setCreatedAt(LocalDateTime.now());
        b2.setUpdatedAt(LocalDateTime.now());

        beneficiaryRepository.save(b1);
        beneficiaryRepository.save(b2);

        // When
        List<Beneficiary> result = beneficiaryRepository.searchBeneficiaries(
                "TEST_CUST_002", null, null, null, null, null, null,
                "beneficiaryName", "ASC", 10, 0
        );

        // Then
        assertThat(result).hasSize(2);
        assertThat(result.get(0).getBeneficiaryName()).isEqualTo("Alice");
        assertThat(result.get(1).getBeneficiaryName()).isEqualTo("Zara");
    }

    @Test
    @DisplayName("Should search beneficiaries with pagination")
    void shouldSearchBeneficiariesWithPagination() {
        // Given
        for (int i = 0; i < 5; i++) {
            Beneficiary b = new Beneficiary();
            b.setCustomerId("TEST_CUST_003");
            b.setAccountNumber("TEST_ACC_003");
            b.setBeneficiaryName("Beneficiary " + i);
            b.setBeneficiaryAccountNumber("BEN_00" + i);
            b.setBeneficiaryBankCode("BANK_003");
            b.setBeneficiaryBankName("Bank 3");
            b.setBeneficiaryType("DOMESTIC");
            b.setStatus("ACTIVE");
            b.setCreatedAt(LocalDateTime.now());
            b.setUpdatedAt(LocalDateTime.now());
            beneficiaryRepository.save(b);
        }

        // When - First page
        List<Beneficiary> page1 = beneficiaryRepository.searchBeneficiaries(
                "TEST_CUST_003", null, null, null, null, null, null,
                "createdAt", "DESC", 2, 0
        );

        // When - Second page
        List<Beneficiary> page2 = beneficiaryRepository.searchBeneficiaries(
                "TEST_CUST_003", null, null, null, null, null, null,
                "createdAt", "DESC", 2, 2
        );

        // Then
        assertThat(page1).hasSize(2);
        assertThat(page2).hasSize(2);
        assertThat(page1.get(0).getId()).isNotEqualTo(page2.get(0).getId());
    }

    @Test
    @DisplayName("Should count beneficiaries with filters")
    void shouldCountBeneficiariesWithFilters() {
        // Given
        testBeneficiary.setBeneficiaryType("INTERNATIONAL");
        beneficiaryRepository.save(testBeneficiary);

        // When
        long count = beneficiaryRepository.countBeneficiaries(
                "TEST_CUST_001",
                "Test",
                "INTERNATIONAL",
                "ACTIVE",
                "TEST_BANK_001",
                LocalDateTime.now().minusDays(1),
                LocalDateTime.now().plusDays(1)
        );

        // Then
        assertThat(count).isGreaterThanOrEqualTo(1);
    }

    @Test
    @DisplayName("Should count all beneficiaries when filters are null")
    void shouldCountAllBeneficiariesWhenFiltersAreNull() {
        // Given
        beneficiaryRepository.save(testBeneficiary);

        // When
        long count = beneficiaryRepository.countBeneficiaries(
                null, null, null, null, null, null, null
        );

        // Then
        assertThat(count).isGreaterThanOrEqualTo(1);
    }

    @Test
    @DisplayName("Should filter by created date range")
    void shouldFilterByCreatedDateRange() {
        // Given
        LocalDateTime now = LocalDateTime.now();
        testBeneficiary.setCreatedAt(now.minusDays(2));
        beneficiaryRepository.save(testBeneficiary);

        // When
        List<Beneficiary> result = beneficiaryRepository.searchBeneficiaries(
                "TEST_CUST_001",
                null, null, null, null,
                now.minusDays(3),
                now.minusDays(1),
                "createdAt", "DESC", 10, 0
        );

        // Then
        assertThat(result).isNotEmpty();
        assertThat(result).allMatch(b -> 
            b.getCreatedAt().isAfter(now.minusDays(3)) && 
            b.getCreatedAt().isBefore(now.minusDays(1))
        );
    }
}
