/**
 * Generated by GitHub Copilot Agent
 * Issue: #generate-tests-for-branch-main
 * Date: 2025-12-18
 * DO NOT EDIT: This test was auto-generated. Review and modify as needed.
 */
package com.alok.payment.beneficiaries.unit.service;

import com.alok.payment.beneficiaries.dto.BeneficiarySearchCriteria;
import com.alok.payment.beneficiaries.dto.PagedResponse;
import com.alok.payment.beneficiaries.model.Beneficiary;
import com.alok.payment.beneficiaries.repository.BeneficiaryRepository;
import com.alok.payment.beneficiaries.service.BeneficiaryService;
import com.alok.payment.beneficiaries.service.BeneficiaryValidationService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
@DisplayName("BeneficiaryService Search Tests")
class BeneficiaryServiceSearchTest {
    
    @Mock
    private BeneficiaryRepository beneficiaryRepository;
    
    @Mock
    private BeneficiaryValidationService validationService;
    
    @InjectMocks
    private BeneficiaryService beneficiaryService;
    
    private List<Beneficiary> testBeneficiaries;
    private BeneficiarySearchCriteria searchCriteria;
    
    @BeforeEach
    void setUp() {
        // Create test beneficiaries
        Beneficiary ben1 = new Beneficiary();
        ben1.setId(1L);
        ben1.setCustomerId("CUST001");
        ben1.setBeneficiaryName("John Doe");
        ben1.setBeneficiaryAccountNumber("ACC001");
        ben1.setBeneficiaryBankCode("BANK001");
        ben1.setBeneficiaryBankName("Bank A");
        ben1.setBeneficiaryType("DOMESTIC");
        ben1.setStatus("ACTIVE");
        ben1.setCreatedAt(LocalDateTime.now().minusDays(5));
        ben1.setUpdatedAt(LocalDateTime.now());
        
        Beneficiary ben2 = new Beneficiary();
        ben2.setId(2L);
        ben2.setCustomerId("CUST001");
        ben2.setBeneficiaryName("Jane Smith");
        ben2.setBeneficiaryAccountNumber("ACC002");
        ben2.setBeneficiaryBankCode("BANK002");
        ben2.setBeneficiaryBankName("Bank B");
        ben2.setBeneficiaryType("INTERNATIONAL");
        ben2.setStatus("ACTIVE");
        ben2.setCreatedAt(LocalDateTime.now().minusDays(3));
        ben2.setUpdatedAt(LocalDateTime.now());
        
        Beneficiary ben3 = new Beneficiary();
        ben3.setId(3L);
        ben3.setCustomerId("CUST001");
        ben3.setBeneficiaryName("Bob Johnson");
        ben3.setBeneficiaryAccountNumber("ACC003");
        ben3.setBeneficiaryBankCode("BANK001");
        ben3.setBeneficiaryBankName("Bank A");
        ben3.setBeneficiaryType("DOMESTIC");
        ben3.setStatus("ACTIVE");
        ben3.setCreatedAt(LocalDateTime.now().minusDays(1));
        ben3.setUpdatedAt(LocalDateTime.now());
        
        testBeneficiaries = Arrays.asList(ben1, ben2, ben3);
        
        // Create default search criteria
        searchCriteria = new BeneficiarySearchCriteria();
        searchCriteria.setCustomerId("CUST001");
        searchCriteria.setPage(0);
        searchCriteria.setSize(20);
        searchCriteria.setSortBy("createdAt");
        searchCriteria.setSortDirection("DESC");
    }
    
    @Test
    @DisplayName("Should search beneficiaries with basic criteria")
    void shouldSearchBeneficiariesWithBasicCriteria() {
        // Given
        when(beneficiaryRepository.searchBeneficiaries(
                anyString(), isNull(), isNull(), isNull(), isNull(), isNull(), isNull(),
                anyString(), anyString(), anyInt(), anyInt()))
                .thenReturn(testBeneficiaries);
        when(beneficiaryRepository.countBeneficiaries(
                anyString(), isNull(), isNull(), isNull(), isNull(), isNull(), isNull()))
                .thenReturn(3L);
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(searchCriteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).hasSize(3);
        assertThat(result.getTotalElements()).isEqualTo(3L);
        assertThat(result.getPage()).isEqualTo(0);
        assertThat(result.getSize()).isEqualTo(20);
        assertThat(result.getTotalPages()).isEqualTo(1);
        assertThat(result.isFirst()).isTrue();
        assertThat(result.isLast()).isTrue();
        
        verify(beneficiaryRepository).searchBeneficiaries(
                eq("CUST001"), isNull(), isNull(), isNull(), isNull(), isNull(), isNull(),
                eq("createdAt"), eq("DESC"), eq(20), eq(0));
        verify(beneficiaryRepository).countBeneficiaries(
                eq("CUST001"), isNull(), isNull(), isNull(), isNull(), isNull(), isNull());
    }
    
    @Test
    @DisplayName("Should search beneficiaries with name filter")
    void shouldSearchBeneficiariesWithNameFilter() {
        // Given
        searchCriteria.setBeneficiaryName("John");
        List<Beneficiary> filtered = Collections.singletonList(testBeneficiaries.get(0));
        
        when(beneficiaryRepository.searchBeneficiaries(
                anyString(), eq("John"), isNull(), isNull(), isNull(), isNull(), isNull(),
                anyString(), anyString(), anyInt(), anyInt()))
                .thenReturn(filtered);
        when(beneficiaryRepository.countBeneficiaries(
                anyString(), eq("John"), isNull(), isNull(), isNull(), isNull(), isNull()))
                .thenReturn(1L);
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(searchCriteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).hasSize(1);
        assertThat(result.getContent().get(0).getBeneficiaryName()).isEqualTo("John Doe");
        assertThat(result.getTotalElements()).isEqualTo(1L);
        
        verify(beneficiaryRepository).searchBeneficiaries(
                eq("CUST001"), eq("John"), isNull(), isNull(), isNull(), isNull(), isNull(),
                eq("createdAt"), eq("DESC"), eq(20), eq(0));
    }
    
    @Test
    @DisplayName("Should search beneficiaries with type filter")
    void shouldSearchBeneficiariesWithTypeFilter() {
        // Given
        searchCriteria.setBeneficiaryType("DOMESTIC");
        List<Beneficiary> filtered = Arrays.asList(testBeneficiaries.get(0), testBeneficiaries.get(2));
        
        when(beneficiaryRepository.searchBeneficiaries(
                anyString(), isNull(), eq("DOMESTIC"), isNull(), isNull(), isNull(), isNull(),
                anyString(), anyString(), anyInt(), anyInt()))
                .thenReturn(filtered);
        when(beneficiaryRepository.countBeneficiaries(
                anyString(), isNull(), eq("DOMESTIC"), isNull(), isNull(), isNull(), isNull()))
                .thenReturn(2L);
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(searchCriteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).hasSize(2);
        assertThat(result.getContent()).allMatch(b -> "DOMESTIC".equals(b.getBeneficiaryType()));
        assertThat(result.getTotalElements()).isEqualTo(2L);
        
        verify(beneficiaryRepository).searchBeneficiaries(
                eq("CUST001"), isNull(), eq("DOMESTIC"), isNull(), isNull(), isNull(), isNull(),
                eq("createdAt"), eq("DESC"), eq(20), eq(0));
    }
    
    @Test
    @DisplayName("Should search beneficiaries with status filter")
    void shouldSearchBeneficiariesWithStatusFilter() {
        // Given
        searchCriteria.setStatus("ACTIVE");
        
        when(beneficiaryRepository.searchBeneficiaries(
                anyString(), isNull(), isNull(), eq("ACTIVE"), isNull(), isNull(), isNull(),
                anyString(), anyString(), anyInt(), anyInt()))
                .thenReturn(testBeneficiaries);
        when(beneficiaryRepository.countBeneficiaries(
                anyString(), isNull(), isNull(), eq("ACTIVE"), isNull(), isNull(), isNull()))
                .thenReturn(3L);
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(searchCriteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).hasSize(3);
        assertThat(result.getContent()).allMatch(b -> "ACTIVE".equals(b.getStatus()));
        assertThat(result.getTotalElements()).isEqualTo(3L);
    }
    
    @Test
    @DisplayName("Should search beneficiaries with bank code filter")
    void shouldSearchBeneficiariesWithBankCodeFilter() {
        // Given
        searchCriteria.setBeneficiaryBankCode("BANK001");
        List<Beneficiary> filtered = Arrays.asList(testBeneficiaries.get(0), testBeneficiaries.get(2));
        
        when(beneficiaryRepository.searchBeneficiaries(
                anyString(), isNull(), isNull(), isNull(), eq("BANK001"), isNull(), isNull(),
                anyString(), anyString(), anyInt(), anyInt()))
                .thenReturn(filtered);
        when(beneficiaryRepository.countBeneficiaries(
                anyString(), isNull(), isNull(), isNull(), eq("BANK001"), isNull(), isNull()))
                .thenReturn(2L);
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(searchCriteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).hasSize(2);
        assertThat(result.getContent()).allMatch(b -> "BANK001".equals(b.getBeneficiaryBankCode()));
        assertThat(result.getTotalElements()).isEqualTo(2L);
    }
    
    @Test
    @DisplayName("Should search beneficiaries with date range filter")
    void shouldSearchBeneficiariesWithDateRangeFilter() {
        // Given
        LocalDateTime startDate = LocalDateTime.now().minusDays(4);
        LocalDateTime endDate = LocalDateTime.now().minusDays(2);
        searchCriteria.setCreatedAfter(startDate);
        searchCriteria.setCreatedBefore(endDate);
        
        List<Beneficiary> filtered = Collections.singletonList(testBeneficiaries.get(1));
        
        when(beneficiaryRepository.searchBeneficiaries(
                anyString(), isNull(), isNull(), isNull(), isNull(), eq(startDate), eq(endDate),
                anyString(), anyString(), anyInt(), anyInt()))
                .thenReturn(filtered);
        when(beneficiaryRepository.countBeneficiaries(
                anyString(), isNull(), isNull(), isNull(), isNull(), eq(startDate), eq(endDate)))
                .thenReturn(1L);
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(searchCriteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).hasSize(1);
        assertThat(result.getTotalElements()).isEqualTo(1L);
    }
    
    @Test
    @DisplayName("Should search beneficiaries with pagination - first page")
    void shouldSearchBeneficiariesWithPaginationFirstPage() {
        // Given
        searchCriteria.setPage(0);
        searchCriteria.setSize(2);
        
        List<Beneficiary> page1 = Arrays.asList(testBeneficiaries.get(0), testBeneficiaries.get(1));
        
        when(beneficiaryRepository.searchBeneficiaries(
                anyString(), isNull(), isNull(), isNull(), isNull(), isNull(), isNull(),
                anyString(), anyString(), eq(2), eq(0)))
                .thenReturn(page1);
        when(beneficiaryRepository.countBeneficiaries(
                anyString(), isNull(), isNull(), isNull(), isNull(), isNull(), isNull()))
                .thenReturn(3L);
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(searchCriteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).hasSize(2);
        assertThat(result.getPage()).isEqualTo(0);
        assertThat(result.getSize()).isEqualTo(2);
        assertThat(result.getTotalElements()).isEqualTo(3L);
        assertThat(result.getTotalPages()).isEqualTo(2);
        assertThat(result.isFirst()).isTrue();
        assertThat(result.isLast()).isFalse();
        
        verify(beneficiaryRepository).searchBeneficiaries(
                eq("CUST001"), isNull(), isNull(), isNull(), isNull(), isNull(), isNull(),
                eq("createdAt"), eq("DESC"), eq(2), eq(0));
    }
    
    @Test
    @DisplayName("Should search beneficiaries with pagination - second page")
    void shouldSearchBeneficiariesWithPaginationSecondPage() {
        // Given
        searchCriteria.setPage(1);
        searchCriteria.setSize(2);
        
        List<Beneficiary> page2 = Collections.singletonList(testBeneficiaries.get(2));
        
        when(beneficiaryRepository.searchBeneficiaries(
                anyString(), isNull(), isNull(), isNull(), isNull(), isNull(), isNull(),
                anyString(), anyString(), eq(2), eq(2)))
                .thenReturn(page2);
        when(beneficiaryRepository.countBeneficiaries(
                anyString(), isNull(), isNull(), isNull(), isNull(), isNull(), isNull()))
                .thenReturn(3L);
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(searchCriteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).hasSize(1);
        assertThat(result.getPage()).isEqualTo(1);
        assertThat(result.getSize()).isEqualTo(2);
        assertThat(result.getTotalElements()).isEqualTo(3L);
        assertThat(result.getTotalPages()).isEqualTo(2);
        assertThat(result.isFirst()).isFalse();
        assertThat(result.isLast()).isTrue();
        
        verify(beneficiaryRepository).searchBeneficiaries(
                eq("CUST001"), isNull(), isNull(), isNull(), isNull(), isNull(), isNull(),
                eq("createdAt"), eq("DESC"), eq(2), eq(2));
    }
    
    @Test
    @DisplayName("Should search beneficiaries with custom sorting - by name ascending")
    void shouldSearchBeneficiariesWithCustomSortingByNameAscending() {
        // Given
        searchCriteria.setSortBy("beneficiaryName");
        searchCriteria.setSortDirection("ASC");
        
        when(beneficiaryRepository.searchBeneficiaries(
                anyString(), isNull(), isNull(), isNull(), isNull(), isNull(), isNull(),
                eq("beneficiaryName"), eq("ASC"), anyInt(), anyInt()))
                .thenReturn(testBeneficiaries);
        when(beneficiaryRepository.countBeneficiaries(
                anyString(), isNull(), isNull(), isNull(), isNull(), isNull(), isNull()))
                .thenReturn(3L);
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(searchCriteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).hasSize(3);
        
        verify(beneficiaryRepository).searchBeneficiaries(
                eq("CUST001"), isNull(), isNull(), isNull(), isNull(), isNull(), isNull(),
                eq("beneficiaryName"), eq("ASC"), eq(20), eq(0));
    }
    
    @Test
    @DisplayName("Should return empty results when no beneficiaries match criteria")
    void shouldReturnEmptyResultsWhenNoBeneficiariesMatchCriteria() {
        // Given
        searchCriteria.setBeneficiaryName("NonExistent");
        
        when(beneficiaryRepository.searchBeneficiaries(
                anyString(), eq("NonExistent"), isNull(), isNull(), isNull(), isNull(), isNull(),
                anyString(), anyString(), anyInt(), anyInt()))
                .thenReturn(Collections.emptyList());
        when(beneficiaryRepository.countBeneficiaries(
                anyString(), eq("NonExistent"), isNull(), isNull(), isNull(), isNull(), isNull()))
                .thenReturn(0L);
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(searchCriteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).isEmpty();
        assertThat(result.getTotalElements()).isEqualTo(0L);
        assertThat(result.getTotalPages()).isEqualTo(0);
        assertThat(result.isFirst()).isTrue();
        assertThat(result.isLast()).isTrue();
    }
    
    @Test
    @DisplayName("Should search beneficiaries with multiple filters")
    void shouldSearchBeneficiariesWithMultipleFilters() {
        // Given
        searchCriteria.setBeneficiaryName("John");
        searchCriteria.setBeneficiaryType("DOMESTIC");
        searchCriteria.setStatus("ACTIVE");
        searchCriteria.setBeneficiaryBankCode("BANK001");
        
        List<Beneficiary> filtered = Collections.singletonList(testBeneficiaries.get(0));
        
        when(beneficiaryRepository.searchBeneficiaries(
                eq("CUST001"), eq("John"), eq("DOMESTIC"), eq("ACTIVE"), eq("BANK001"), isNull(), isNull(),
                anyString(), anyString(), anyInt(), anyInt()))
                .thenReturn(filtered);
        when(beneficiaryRepository.countBeneficiaries(
                eq("CUST001"), eq("John"), eq("DOMESTIC"), eq("ACTIVE"), eq("BANK001"), isNull(), isNull()))
                .thenReturn(1L);
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(searchCriteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).hasSize(1);
        assertThat(result.getContent().get(0).getBeneficiaryName()).isEqualTo("John Doe");
        assertThat(result.getContent().get(0).getBeneficiaryType()).isEqualTo("DOMESTIC");
        assertThat(result.getContent().get(0).getBeneficiaryBankCode()).isEqualTo("BANK001");
        assertThat(result.getTotalElements()).isEqualTo(1L);
    }
    
    @Test
    @DisplayName("Should calculate total pages correctly")
    void shouldCalculateTotalPagesCorrectly() {
        // Given
        searchCriteria.setSize(2);
        
        List<Beneficiary> page = Arrays.asList(testBeneficiaries.get(0), testBeneficiaries.get(1));
        
        when(beneficiaryRepository.searchBeneficiaries(
                anyString(), isNull(), isNull(), isNull(), isNull(), isNull(), isNull(),
                anyString(), anyString(), eq(2), anyInt()))
                .thenReturn(page);
        when(beneficiaryRepository.countBeneficiaries(
                anyString(), isNull(), isNull(), isNull(), isNull(), isNull(), isNull()))
                .thenReturn(5L); // 5 total elements, 2 per page = 3 pages
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(searchCriteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getTotalElements()).isEqualTo(5L);
        assertThat(result.getSize()).isEqualTo(2);
        assertThat(result.getTotalPages()).isEqualTo(3);
    }
    
    @Test
    @DisplayName("Should handle null customer ID in search criteria")
    void shouldHandleNullCustomerIdInSearchCriteria() {
        // Given
        searchCriteria.setCustomerId(null);
        
        when(beneficiaryRepository.searchBeneficiaries(
                isNull(), isNull(), isNull(), isNull(), isNull(), isNull(), isNull(),
                anyString(), anyString(), anyInt(), anyInt()))
                .thenReturn(testBeneficiaries);
        when(beneficiaryRepository.countBeneficiaries(
                isNull(), isNull(), isNull(), isNull(), isNull(), isNull(), isNull()))
                .thenReturn(3L);
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(searchCriteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).hasSize(3);
        
        verify(beneficiaryRepository).searchBeneficiaries(
                isNull(), isNull(), isNull(), isNull(), isNull(), isNull(), isNull(),
                eq("createdAt"), eq("DESC"), eq(20), eq(0));
    }
    
    @Test
    @DisplayName("Should use default values from criteria when not specified")
    void shouldUseDefaultValuesFromCriteriaWhenNotSpecified() {
        // Given - Create criteria with defaults
        BeneficiarySearchCriteria defaultCriteria = new BeneficiarySearchCriteria();
        
        when(beneficiaryRepository.searchBeneficiaries(
                isNull(), isNull(), isNull(), isNull(), isNull(), isNull(), isNull(),
                eq("createdAt"), eq("DESC"), eq(20), eq(0)))
                .thenReturn(testBeneficiaries);
        when(beneficiaryRepository.countBeneficiaries(
                isNull(), isNull(), isNull(), isNull(), isNull(), isNull(), isNull()))
                .thenReturn(3L);
        
        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(defaultCriteria);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getPage()).isEqualTo(0);
        assertThat(result.getSize()).isEqualTo(20);
        
        verify(beneficiaryRepository).searchBeneficiaries(
                isNull(), isNull(), isNull(), isNull(), isNull(), isNull(), isNull(),
                eq("createdAt"), eq("DESC"), eq(20), eq(0));
    }
}
