/**
 * Generated by GitHub Copilot Agent
 * Issue: #0
 * Date: 2025-12-18
 * DO NOT EDIT: This test was auto-generated. Review and modify as needed.
 */
package com.alok.payment.beneficiaries.integration.service;

import com.alok.payment.beneficiaries.dto.BeneficiarySearchCriteria;
import com.alok.payment.beneficiaries.dto.PagedResponse;
import com.alok.payment.beneficiaries.model.Beneficiary;
import com.alok.payment.beneficiaries.repository.BeneficiaryRepository;
import com.alok.payment.beneficiaries.service.BeneficiaryService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.images.PullPolicy;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
@Testcontainers
@DisplayName("BeneficiaryService Integration Tests - Search and Analytics")
class BeneficiaryServiceSearchAnalyticsIntegrationTest {

    @SuppressWarnings("resource")
    @Container
    static final PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>(
            DockerImageName.parse("ghcr.io/alokkulkarni/testcontainers-registry/testcontainers/postgres:16-alpine").asCompatibleSubstituteFor("postgres"))
            .withImagePullPolicy(PullPolicy.defaultPolicy())
            .withDatabaseName("beneficiaries_test")
            .withUsername("test")
            .withPassword("test")
            .withInitScript("init.db");

    @SuppressWarnings("resource")
    @Container
    static final GenericContainer<?> redis = new GenericContainer<>(
            DockerImageName.parse("ghcr.io/alokkulkarni/testcontainers-registry/testcontainers/redis:7-alpine").asCompatibleSubstituteFor("redis"))
            .withImagePullPolicy(PullPolicy.defaultPolicy())
            .withExposedPorts(6379);

    @DynamicPropertySource
    static void configureProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", postgres::getJdbcUrl);
        registry.add("spring.datasource.username", postgres::getUsername);
        registry.add("spring.datasource.password", postgres::getPassword);
        registry.add("spring.data.redis.host", redis::getHost);
        registry.add("spring.data.redis.port", redis::getFirstMappedPort);
    }

    @Autowired
    private BeneficiaryService beneficiaryService;

    @Autowired
    private BeneficiaryRepository beneficiaryRepository;

    private String testCustomerId;

    @BeforeEach
    void setUp() {
        testCustomerId = "SVC_INT_TEST_CUST_" + System.currentTimeMillis();
        
        // Create test beneficiaries
        LocalDateTime now = LocalDateTime.now();
        
        for (int i = 0; i < 15; i++) {
            Beneficiary b = new Beneficiary();
            b.setCustomerId(testCustomerId);
            b.setAccountNumber("SVC_INT_ACC_" + i);
            b.setBeneficiaryName(i % 3 == 0 ? "Alpha Corp " + i : "Beta Corp " + i);
            b.setBeneficiaryAccountNumber("SVC_INT_BEN_" + i);
            b.setBeneficiaryBankCode(i % 2 == 0 ? "BANK_A" : "BANK_B");
            b.setBeneficiaryBankName(i % 2 == 0 ? "Bank A" : "Bank B");
            b.setBeneficiaryType(i % 3 == 0 ? "INTERNATIONAL" : "DOMESTIC");
            b.setStatus(i < 12 ? "ACTIVE" : "INACTIVE");
            b.setCreatedAt(now.minusDays(15 - i));
            b.setUpdatedAt(now);
            beneficiaryRepository.save(b);
        }
    }

    @Test
    @DisplayName("Should search beneficiaries with pagination integration test")
    void shouldSearchBeneficiariesWithPagination() {
        // Given
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId(testCustomerId);
        criteria.setPage(0);
        criteria.setSize(5);
        criteria.setSortBy("createdAt");
        criteria.setSortDirection("DESC");

        // When
        PagedResponse<Beneficiary> page1 = beneficiaryService.searchBeneficiaries(criteria);
        
        criteria.setPage(1);
        PagedResponse<Beneficiary> page2 = beneficiaryService.searchBeneficiaries(criteria);

        // Then
        assertThat(page1.getContent()).hasSize(5);
        assertThat(page2.getContent()).hasSize(5);
        assertThat(page1.getTotalElements()).isEqualTo(15);
        assertThat(page1.getTotalPages()).isEqualTo(3);
        assertThat(page1.isFirst()).isTrue();
        assertThat(page1.isLast()).isFalse();
        assertThat(page2.isFirst()).isFalse();
        assertThat(page2.isLast()).isFalse();
        
        // Pages should have different content
        assertThat(page1.getContent().get(0).getId())
                .isNotEqualTo(page2.getContent().get(0).getId());
    }

    @Test
    @DisplayName("Should search beneficiaries by name")
    void shouldSearchBeneficiariesByName() {
        // Given
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId(testCustomerId);
        criteria.setBeneficiaryName("Alpha");

        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(criteria);

        // Then
        assertThat(result.getContent()).isNotEmpty();
        assertThat(result.getContent()).allMatch(b -> b.getBeneficiaryName().contains("Alpha"));
    }

    @Test
    @DisplayName("Should search beneficiaries by type")
    void shouldSearchBeneficiariesByType() {
        // Given
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId(testCustomerId);
        criteria.setBeneficiaryType("INTERNATIONAL");

        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(criteria);

        // Then
        assertThat(result.getContent()).isNotEmpty();
        assertThat(result.getContent()).allMatch(b -> "INTERNATIONAL".equals(b.getBeneficiaryType()));
    }

    @Test
    @DisplayName("Should search beneficiaries by status")
    void shouldSearchBeneficiariesByStatus() {
        // Given
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId(testCustomerId);
        criteria.setStatus("INACTIVE");

        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(criteria);

        // Then
        assertThat(result.getContent()).hasSize(3);
        assertThat(result.getContent()).allMatch(b -> "INACTIVE".equals(b.getStatus()));
    }

    @Test
    @DisplayName("Should get customer beneficiary analytics")
    void shouldGetCustomerBeneficiaryAnalytics() {
        // When
        Map<String, Object> analytics = beneficiaryService.getCustomerBeneficiaryAnalytics(testCustomerId);

        // Then
        assertThat(analytics).isNotNull();
        assertThat(analytics.get("customerId")).isEqualTo(testCustomerId);
        assertThat(analytics.get("totalBeneficiaries")).isEqualTo(15);
        assertThat(analytics.get("activeBeneficiaries")).isEqualTo(12L);
        assertThat(analytics.get("inactiveBeneficiaries")).isEqualTo(3L);

        @SuppressWarnings("unchecked")
        Map<String, Long> byType = (Map<String, Long>) analytics.get("beneficiariesByType");
        assertThat(byType).isNotNull();
        assertThat(byType.get("INTERNATIONAL")).isEqualTo(5L);
        assertThat(byType.get("DOMESTIC")).isEqualTo(10L);

        @SuppressWarnings("unchecked")
        Map<String, Long> byBank = (Map<String, Long>) analytics.get("beneficiariesByBank");
        assertThat(byBank).isNotNull();
        assertThat(byBank.get("Bank A")).isEqualTo(8L);
        assertThat(byBank.get("Bank B")).isEqualTo(7L);

        assertThat(analytics.get("mostRecentBeneficiaryName")).isNotNull();
        assertThat(analytics.get("mostRecentAddedAt")).isNotNull();
    }

    @Test
    @DisplayName("Should find potential duplicates")
    void shouldFindPotentialDuplicates() {
        // Given - Create beneficiaries with similar names
        LocalDateTime now = LocalDateTime.now();
        
        Beneficiary b1 = new Beneficiary();
        b1.setCustomerId(testCustomerId);
        b1.setAccountNumber("DUP_ACC_1");
        b1.setBeneficiaryName("John Doe");
        b1.setBeneficiaryAccountNumber("DUP_BEN_1");
        b1.setBeneficiaryBankCode("BANK_X");
        b1.setBeneficiaryBankName("Bank X");
        b1.setBeneficiaryType("DOMESTIC");
        b1.setStatus("ACTIVE");
        b1.setCreatedAt(now);
        b1.setUpdatedAt(now);
        beneficiaryRepository.save(b1);

        Beneficiary b2 = new Beneficiary();
        b2.setCustomerId(testCustomerId);
        b2.setAccountNumber("DUP_ACC_2");
        b2.setBeneficiaryName("JohnDoe");
        b2.setBeneficiaryAccountNumber("DUP_BEN_2");
        b2.setBeneficiaryBankCode("BANK_X");
        b2.setBeneficiaryBankName("Bank X");
        b2.setBeneficiaryType("DOMESTIC");
        b2.setStatus("ACTIVE");
        b2.setCreatedAt(now);
        b2.setUpdatedAt(now);
        beneficiaryRepository.save(b2);

        // When
        List<Map<String, Object>> duplicates = beneficiaryService.findPotentialDuplicates(testCustomerId);

        // Then
        assertThat(duplicates).isNotEmpty();
        assertThat(duplicates).anySatisfy(dup -> {
            assertThat(dup.get("similarity")).isEqualTo("HIGH");
            String name1 = (String) dup.get("beneficiary1Name");
            String name2 = (String) dup.get("beneficiary2Name");
            assertThat(name1.replace(" ", "").toLowerCase())
                    .isEqualTo(name2.replace(" ", "").toLowerCase());
        });
    }

    @Test
    @DisplayName("Should generate beneficiary usage report")
    void shouldGenerateBeneficiaryUsageReport() {
        // Given
        LocalDateTime now = LocalDateTime.now();
        LocalDateTime startDate = now.minusDays(7);
        LocalDateTime endDate = now.plusDays(1);

        // When
        Map<String, Object> report = beneficiaryService.getBeneficiaryUsageReport(
                testCustomerId, startDate, endDate);

        // Then
        assertThat(report).isNotNull();
        assertThat(report.get("customerId")).isEqualTo(testCustomerId);
        assertThat(report.get("reportPeriodStart")).isEqualTo(startDate);
        assertThat(report.get("reportPeriodEnd")).isEqualTo(endDate);
        assertThat(report.get("totalBeneficiaries")).isEqualTo(15);
        
        Integer beneficiariesInPeriod = (Integer) report.get("beneficiariesAddedInPeriod");
        assertThat(beneficiariesInPeriod).isGreaterThanOrEqualTo(0);
        assertThat(beneficiariesInPeriod).isLessThanOrEqualTo(15);
        
        assertThat(report.get("growthRatePercent")).isInstanceOf(Double.class);
    }

    @Test
    @DisplayName("Should search with multiple filters combined")
    void shouldSearchWithMultipleFiltersCombined() {
        // Given
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId(testCustomerId);
        criteria.setBeneficiaryName("Alpha");
        criteria.setBeneficiaryType("INTERNATIONAL");
        criteria.setStatus("ACTIVE");

        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(criteria);

        // Then
        assertThat(result.getContent()).isNotEmpty();
        assertThat(result.getContent()).allMatch(b -> 
            b.getBeneficiaryName().contains("Alpha") &&
            "INTERNATIONAL".equals(b.getBeneficiaryType()) &&
            "ACTIVE".equals(b.getStatus())
        );
    }

    @Test
    @DisplayName("Should search with date range filter")
    void shouldSearchWithDateRangeFilter() {
        // Given
        LocalDateTime now = LocalDateTime.now();
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId(testCustomerId);
        criteria.setCreatedAfter(now.minusDays(5));
        criteria.setCreatedBefore(now.plusDays(1));

        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(criteria);

        // Then
        assertThat(result.getContent()).isNotEmpty();
        assertThat(result.getContent()).allMatch(b -> 
            b.getCreatedAt().isAfter(now.minusDays(5)) &&
            b.getCreatedAt().isBefore(now.plusDays(1))
        );
    }

    @Test
    @DisplayName("Should sort results by name ascending")
    void shouldSortResultsByNameAscending() {
        // Given
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId(testCustomerId);
        criteria.setSortBy("beneficiaryName");
        criteria.setSortDirection("ASC");
        criteria.setSize(20);

        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(criteria);

        // Then
        assertThat(result.getContent()).isNotEmpty();
        
        // Verify ascending order
        for (int i = 0; i < result.getContent().size() - 1; i++) {
            String name1 = result.getContent().get(i).getBeneficiaryName();
            String name2 = result.getContent().get(i + 1).getBeneficiaryName();
            assertThat(name1.compareTo(name2)).isLessThanOrEqualTo(0);
        }
    }

    @Test
    @DisplayName("Should handle empty search results")
    void shouldHandleEmptySearchResults() {
        // Given
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId("NON_EXISTENT_CUSTOMER");

        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(criteria);

        // Then
        assertThat(result).isNotNull();
        assertThat(result.getContent()).isEmpty();
        assertThat(result.getTotalElements()).isEqualTo(0);
        assertThat(result.getTotalPages()).isEqualTo(0);
    }

    @Test
    @DisplayName("Should calculate correct total pages")
    void shouldCalculateCorrectTotalPages() {
        // Given
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId(testCustomerId);
        criteria.setSize(4); // 15 items / 4 per page = 4 pages

        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(criteria);

        // Then
        assertThat(result.getTotalElements()).isEqualTo(15);
        assertThat(result.getTotalPages()).isEqualTo(4); // ceil(15/4) = 4
    }

    @Test
    @DisplayName("Should search by bank code filter")
    void shouldSearchByBankCodeFilter() {
        // Given
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId(testCustomerId);
        criteria.setBeneficiaryBankCode("BANK_A");

        // When
        PagedResponse<Beneficiary> result = beneficiaryService.searchBeneficiaries(criteria);

        // Then
        assertThat(result.getContent()).isNotEmpty();
        assertThat(result.getContent()).allMatch(b -> "BANK_A".equals(b.getBeneficiaryBankCode()));
    }
}
