/**
 * Generated by GitHub Copilot Agent
 * Issue: #generate-tests-for-branch-main
 * Date: 2025-12-18
 * DO NOT EDIT: This test was auto-generated. Review and modify as needed.
 */
package com.alok.payment.beneficiaries.bdd.steps;

import com.alok.payment.beneficiaries.bdd.context.TestContext;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

public class AnalyticsSteps {
    
    private final TestContext testContext;
    
    public AnalyticsSteps(TestContext testContext) {
        this.testContext = testContext;
    }
    
    @When("I request analytics for customer {string}")
    public void iRequestAnalyticsForCustomer(String customerId) {
        Map<String, Object> analytics = testContext.getBeneficiaryService()
                .getCustomerBeneficiaryAnalytics(customerId);
        testContext.setAnalyticsResponse(analytics);
    }
    
    @When("I request potential duplicates for customer {string}")
    public void iRequestPotentialDuplicatesForCustomer(String customerId) {
        List<Map<String, Object>> duplicates = testContext.getBeneficiaryService()
                .findPotentialDuplicates(customerId);
        testContext.setDuplicatesResponse(duplicates);
    }
    
    @When("I request usage report for customer {string} for the last {int} days")
    public void iRequestUsageReportForCustomerForLastDays(String customerId, int days) {
        LocalDateTime startDate = LocalDateTime.now().minusDays(days);
        LocalDateTime endDate = LocalDateTime.now().plusDays(1);
        
        Map<String, Object> report = testContext.getBeneficiaryService()
                .getBeneficiaryUsageReport(customerId, startDate, endDate);
        testContext.setUsageReportResponse(report);
    }
    
    @Then("the analytics should include total beneficiaries count")
    public void theAnalyticsShouldIncludeTotalBeneficiariesCount() {
        Map<String, Object> analytics = testContext.getAnalyticsResponse();
        assertThat(analytics).isNotNull();
        assertThat(analytics).containsKey("totalBeneficiaries");
        assertThat(analytics.get("totalBeneficiaries")).isNotNull();
    }
    
    @Then("the analytics should include active beneficiaries count")
    public void theAnalyticsShouldIncludeActiveBeneficiariesCount() {
        Map<String, Object> analytics = testContext.getAnalyticsResponse();
        assertThat(analytics).isNotNull();
        assertThat(analytics).containsKey("activeBeneficiaries");
        assertThat(analytics.get("activeBeneficiaries")).isNotNull();
    }
    
    @Then("the analytics should include inactive beneficiaries count")
    public void theAnalyticsShouldIncludeInactiveBeneficiariesCount() {
        Map<String, Object> analytics = testContext.getAnalyticsResponse();
        assertThat(analytics).isNotNull();
        assertThat(analytics).containsKey("inactiveBeneficiaries");
        assertThat(analytics.get("inactiveBeneficiaries")).isNotNull();
    }
    
    @Then("the analytics should include beneficiaries grouped by type")
    public void theAnalyticsShouldIncludeBeneficiariesGroupedByType() {
        Map<String, Object> analytics = testContext.getAnalyticsResponse();
        assertThat(analytics).isNotNull();
        assertThat(analytics).containsKey("beneficiariesByType");
        assertThat(analytics.get("beneficiariesByType")).isNotNull();
    }
    
    @Then("the analytics should include beneficiaries grouped by bank")
    public void theAnalyticsShouldIncludeBeneficiariesGroupedByBank() {
        Map<String, Object> analytics = testContext.getAnalyticsResponse();
        assertThat(analytics).isNotNull();
        assertThat(analytics).containsKey("beneficiariesByBank");
        assertThat(analytics.get("beneficiariesByBank")).isNotNull();
    }
    
    @Then("the analytics should include most recent beneficiary name")
    public void theAnalyticsShouldIncludeMostRecentBeneficiaryName() {
        Map<String, Object> analytics = testContext.getAnalyticsResponse();
        assertThat(analytics).isNotNull();
        // May or may not have this field depending on data
        if (analytics.containsKey("mostRecentBeneficiaryName")) {
            assertThat(analytics.get("mostRecentBeneficiaryName")).isNotNull();
        }
    }
    
    @Then("the analytics should include most recent added date")
    public void theAnalyticsShouldIncludeMostRecentAddedDate() {
        Map<String, Object> analytics = testContext.getAnalyticsResponse();
        assertThat(analytics).isNotNull();
        // May or may not have this field depending on data
        if (analytics.containsKey("mostRecentAddedAt")) {
            assertThat(analytics.get("mostRecentAddedAt")).isNotNull();
        }
    }
    
    @Then("the analytics should show zero total beneficiaries")
    public void theAnalyticsShouldShowZeroTotalBeneficiaries() {
        Map<String, Object> analytics = testContext.getAnalyticsResponse();
        assertThat(analytics).isNotNull();
        assertThat(analytics).containsKey("totalBeneficiaries");
        assertThat((Integer) analytics.get("totalBeneficiaries")).isEqualTo(0);
    }
    
    @Then("the analytics should show zero active beneficiaries")
    public void theAnalyticsShouldShowZeroActiveBeneficiaries() {
        Map<String, Object> analytics = testContext.getAnalyticsResponse();
        assertThat(analytics).isNotNull();
        assertThat(analytics).containsKey("activeBeneficiaries");
        assertThat((Long) analytics.get("activeBeneficiaries")).isEqualTo(0L);
    }
    
    @Then("the duplicate search should complete successfully")
    public void theDuplicateSearchShouldCompleteSuccessfully() {
        List<Map<String, Object>> duplicates = testContext.getDuplicatesResponse();
        assertThat(duplicates).isNotNull();
    }
    
    @Then("the report should include total beneficiaries")
    public void theReportShouldIncludeTotalBeneficiaries() {
        Map<String, Object> report = testContext.getUsageReportResponse();
        assertThat(report).isNotNull();
        assertThat(report).containsKey("totalBeneficiaries");
        assertThat(report.get("totalBeneficiaries")).isNotNull();
    }
    
    @Then("the report should include beneficiaries added in period")
    public void theReportShouldIncludeBeneficiariesAddedInPeriod() {
        Map<String, Object> report = testContext.getUsageReportResponse();
        assertThat(report).isNotNull();
        assertThat(report).containsKey("beneficiariesAddedInPeriod");
        assertThat(report.get("beneficiariesAddedInPeriod")).isNotNull();
    }
    
    @Then("the report should include growth rate percentage")
    public void theReportShouldIncludeGrowthRatePercentage() {
        Map<String, Object> report = testContext.getUsageReportResponse();
        assertThat(report).isNotNull();
        assertThat(report).containsKey("growthRatePercent");
        assertThat(report.get("growthRatePercent")).isNotNull();
    }
    
    @Then("the report should include report period dates")
    public void theReportShouldIncludeReportPeriodDates() {
        Map<String, Object> report = testContext.getUsageReportResponse();
        assertThat(report).isNotNull();
        assertThat(report).containsKey("reportPeriodStart");
        assertThat(report).containsKey("reportPeriodEnd");
        assertThat(report.get("reportPeriodStart")).isNotNull();
        assertThat(report.get("reportPeriodEnd")).isNotNull();
    }
    
    @Then("the type breakdown should contain valid beneficiary types")
    public void theTypeBreakdownShouldContainValidBeneficiaryTypes() {
        Map<String, Object> analytics = testContext.getAnalyticsResponse();
        assertThat(analytics).isNotNull();
        
        @SuppressWarnings("unchecked")
        Map<String, Long> byType = (Map<String, Long>) analytics.get("beneficiariesByType");
        assertThat(byType).isNotNull();
        
        // Verify that types are either DOMESTIC, INTERNATIONAL, or other valid types
        for (String type : byType.keySet()) {
            assertThat(type).isNotNull();
            assertThat(byType.get(type)).isGreaterThanOrEqualTo(0L);
        }
    }
    
    @Then("the bank breakdown should contain bank names")
    public void theBankBreakdownShouldContainBankNames() {
        Map<String, Object> analytics = testContext.getAnalyticsResponse();
        assertThat(analytics).isNotNull();
        
        @SuppressWarnings("unchecked")
        Map<String, Long> byBank = (Map<String, Long>) analytics.get("beneficiariesByBank");
        assertThat(byBank).isNotNull();
        
        // Verify that all values are non-negative
        for (Long count : byBank.values()) {
            assertThat(count).isGreaterThanOrEqualTo(0L);
        }
    }
}
