/**
 * Generated by GitHub Copilot Agent
 * Issue: #generate-tests-for-branch-main
 * Date: 2025-12-18
 * DO NOT EDIT: This test was auto-generated. Review and modify as needed.
 */
package com.alok.payment.beneficiaries.bdd.steps;

import com.alok.payment.beneficiaries.bdd.context.TestContext;
import com.alok.payment.beneficiaries.dto.BeneficiarySearchCriteria;
import com.alok.payment.beneficiaries.dto.PagedResponse;
import com.alok.payment.beneficiaries.model.Beneficiary;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

import java.time.LocalDateTime;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

public class SearchBeneficiarySteps {
    
    private final TestContext testContext;
    
    public SearchBeneficiarySteps(TestContext testContext) {
        this.testContext = testContext;
    }
    
    @When("I search for beneficiaries with customerId {string}")
    public void iSearchForBeneficiariesWithCustomerId(String customerId) {
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId(customerId);
        
        PagedResponse<Beneficiary> response = testContext.getBeneficiaryService()
                .searchBeneficiaries(criteria);
        testContext.setSearchResponse(response);
    }
    
    @When("I search for beneficiaries with name containing {string}")
    public void iSearchForBeneficiariesWithNameContaining(String name) {
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setBeneficiaryName(name);
        
        PagedResponse<Beneficiary> response = testContext.getBeneficiaryService()
                .searchBeneficiaries(criteria);
        testContext.setSearchResponse(response);
    }
    
    @When("I search for beneficiaries with type {string}")
    public void iSearchForBeneficiariesWithType(String type) {
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setBeneficiaryType(type);
        
        PagedResponse<Beneficiary> response = testContext.getBeneficiaryService()
                .searchBeneficiaries(criteria);
        testContext.setSearchResponse(response);
    }
    
    @When("I search for beneficiaries with status {string}")
    public void iSearchForBeneficiariesWithStatus(String status) {
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setStatus(status);
        
        PagedResponse<Beneficiary> response = testContext.getBeneficiaryService()
                .searchBeneficiaries(criteria);
        testContext.setSearchResponse(response);
    }
    
    @When("I search for beneficiaries with customerId {string} page {int} and size {int}")
    public void iSearchForBeneficiariesWithPagination(String customerId, int page, int size) {
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId(customerId);
        criteria.setPage(page);
        criteria.setSize(size);
        
        PagedResponse<Beneficiary> response = testContext.getBeneficiaryService()
                .searchBeneficiaries(criteria);
        testContext.setSearchResponse(response);
    }
    
    @When("I search for beneficiaries with customerId {string} sorted by {string} in {string} order")
    public void iSearchForBeneficiariesWithSorting(String customerId, String sortBy, String sortDirection) {
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId(customerId);
        criteria.setSortBy(sortBy);
        criteria.setSortDirection(sortDirection);
        
        PagedResponse<Beneficiary> response = testContext.getBeneficiaryService()
                .searchBeneficiaries(criteria);
        testContext.setSearchResponse(response);
    }
    
    @When("I search for beneficiaries with customerId {string} and type {string}")
    public void iSearchForBeneficiariesWithMultipleFilters(String customerId, String type) {
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCustomerId(customerId);
        criteria.setBeneficiaryType(type);
        
        PagedResponse<Beneficiary> response = testContext.getBeneficiaryService()
                .searchBeneficiaries(criteria);
        testContext.setSearchResponse(response);
    }
    
    @When("I search for beneficiaries with bankCode {string}")
    public void iSearchForBeneficiariesWithBankCode(String bankCode) {
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setBeneficiaryBankCode(bankCode);
        
        PagedResponse<Beneficiary> response = testContext.getBeneficiaryService()
                .searchBeneficiaries(criteria);
        testContext.setSearchResponse(response);
    }
    
    @When("I search for beneficiaries created in the last {int} days")
    public void iSearchForBeneficiariesCreatedInLastDays(int days) {
        BeneficiarySearchCriteria criteria = new BeneficiarySearchCriteria();
        criteria.setCreatedAfter(LocalDateTime.now().minusDays(days));
        criteria.setCreatedBefore(LocalDateTime.now().plusDays(1));
        
        PagedResponse<Beneficiary> response = testContext.getBeneficiaryService()
                .searchBeneficiaries(criteria);
        testContext.setSearchResponse(response);
    }
    
    @Then("the search should return beneficiaries")
    public void theSearchShouldReturnBeneficiaries() {
        PagedResponse<Beneficiary> response = testContext.getSearchResponse();
        assertThat(response).isNotNull();
        assertThat(response.getContent()).isNotNull();
        assertThat(response.getContent()).isNotEmpty();
    }
    
    @Then("the search should return {int} beneficiaries")
    public void theSearchShouldReturnSpecificNumberOfBeneficiaries(int expectedCount) {
        PagedResponse<Beneficiary> response = testContext.getSearchResponse();
        assertThat(response).isNotNull();
        assertThat(response.getContent()).hasSize(expectedCount);
    }
    
    @Then("the search should return empty results")
    public void theSearchShouldReturnEmptyResults() {
        PagedResponse<Beneficiary> response = testContext.getSearchResponse();
        assertThat(response).isNotNull();
        assertThat(response.getContent()).isEmpty();
    }
    
    @Then("all beneficiaries should belong to customer {string}")
    public void allBeneficiariesShouldBelongToCustomer(String customerId) {
        PagedResponse<Beneficiary> response = testContext.getSearchResponse();
        assertThat(response).isNotNull();
        assertThat(response.getContent()).isNotEmpty();
        assertThat(response.getContent()).allMatch(b -> customerId.equals(b.getCustomerId()));
    }
    
    @Then("all beneficiaries should have name containing {string}")
    public void allBeneficiariesShouldHaveNameContaining(String name) {
        PagedResponse<Beneficiary> response = testContext.getSearchResponse();
        assertThat(response).isNotNull();
        assertThat(response.getContent()).isNotEmpty();
        assertThat(response.getContent()).allMatch(b -> 
                b.getBeneficiaryName() != null && 
                b.getBeneficiaryName().toLowerCase().contains(name.toLowerCase()));
    }
    
    @Then("all beneficiaries should be of type {string}")
    public void allBeneficiariesShouldBeOfType(String type) {
        PagedResponse<Beneficiary> response = testContext.getSearchResponse();
        assertThat(response).isNotNull();
        assertThat(response.getContent()).isNotEmpty();
        assertThat(response.getContent()).allMatch(b -> type.equals(b.getBeneficiaryType()));
    }
    
    @Then("all beneficiaries should have status {string}")
    public void allBeneficiariesShouldHaveStatus(String status) {
        PagedResponse<Beneficiary> response = testContext.getSearchResponse();
        assertThat(response).isNotNull();
        assertThat(response.getContent()).isNotEmpty();
        assertThat(response.getContent()).allMatch(b -> status.equals(b.getStatus()));
    }
    
    @Then("all beneficiaries should have bankCode {string}")
    public void allBeneficiariesShouldHaveBankCode(String bankCode) {
        PagedResponse<Beneficiary> response = testContext.getSearchResponse();
        assertThat(response).isNotNull();
        assertThat(response.getContent()).isNotEmpty();
        assertThat(response.getContent()).allMatch(b -> bankCode.equals(b.getBeneficiaryBankCode()));
    }
    
    @Then("the page should be {int}")
    public void thePageShouldBe(int expectedPage) {
        PagedResponse<Beneficiary> response = testContext.getSearchResponse();
        assertThat(response).isNotNull();
        assertThat(response.getPage()).isEqualTo(expectedPage);
    }
    
    @Then("the result should indicate it is the first page")
    public void theResultShouldIndicateItIsTheFirstPage() {
        PagedResponse<Beneficiary> response = testContext.getSearchResponse();
        assertThat(response).isNotNull();
        assertThat(response.isFirst()).isTrue();
    }
    
    @Then("the beneficiaries should be sorted by name in ascending order")
    public void theBeneficiariesShouldBeSortedByNameInAscendingOrder() {
        PagedResponse<Beneficiary> response = testContext.getSearchResponse();
        assertThat(response).isNotNull();
        
        List<Beneficiary> beneficiaries = response.getContent();
        for (int i = 1; i < beneficiaries.size(); i++) {
            String prev = beneficiaries.get(i - 1).getBeneficiaryName();
            String curr = beneficiaries.get(i).getBeneficiaryName();
            assertThat(prev.compareTo(curr)).isLessThanOrEqualTo(0);
        }
    }
    
    @Then("the total count should be {int}")
    public void theTotalCountShouldBe(int expectedCount) {
        PagedResponse<Beneficiary> response = testContext.getSearchResponse();
        assertThat(response).isNotNull();
        assertThat(response.getTotalElements()).isEqualTo(expectedCount);
    }
    
    @Then("all beneficiaries should be created within the date range")
    public void allBeneficiariesShouldBeCreatedWithinTheDateRange() {
        PagedResponse<Beneficiary> response = testContext.getSearchResponse();
        assertThat(response).isNotNull();
        assertThat(response.getContent()).isNotEmpty();
        // Just verify that all beneficiaries have creation dates
        assertThat(response.getContent()).allMatch(b -> b.getCreatedAt() != null);
    }
}
