/**
 * Generated by GitHub Copilot Agent
 * Issue: #0
 * Date: 2025-12-18
 * NOTE: This test was auto-generated. Review and modify as needed.
 */
package com.alok.payment.beneficiaries.bdd.steps;

import com.alok.payment.beneficiaries.bdd.context.TestContext;
import com.alok.payment.beneficiaries.dto.BeneficiarySearchCriteria;
import com.alok.payment.beneficiaries.dto.PagedResponse;
import com.alok.payment.beneficiaries.model.Beneficiary;
import com.alok.payment.beneficiaries.repository.BeneficiaryRepository;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.HttpMethod;
import org.springframework.http.ResponseEntity;
import org.springframework.web.util.UriComponentsBuilder;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

public class SearchBeneficiarySteps {

    @Autowired
    private TestRestTemplate restTemplate;

    @Autowired
    private TestContext testContext;

    @Autowired
    private BeneficiaryRepository beneficiaryRepository;

    @When("I search for beneficiaries with customerId {string}")
    public void iSearchForBeneficiariesWithCustomerId(String customerId) {
        String url = UriComponentsBuilder.fromPath("/api/v1/beneficiaries/search")
                .queryParam("customerId", customerId)
                .toUriString();

        ResponseEntity<PagedResponse<Beneficiary>> response = restTemplate.exchange(
                url,
                HttpMethod.GET,
                null,
                new ParameterizedTypeReference<PagedResponse<Beneficiary>>() {}
        );

        testContext.setResponse(response);
        testContext.setPagedResponse(response.getBody());
    }

    @When("I search for beneficiaries with customerId {string} and name {string}")
    public void iSearchForBeneficiariesWithCustomerIdAndName(String customerId, String name) {
        String url = UriComponentsBuilder.fromPath("/api/v1/beneficiaries/search")
                .queryParam("customerId", customerId)
                .queryParam("beneficiaryName", name)
                .toUriString();

        ResponseEntity<PagedResponse<Beneficiary>> response = restTemplate.exchange(
                url,
                HttpMethod.GET,
                null,
                new ParameterizedTypeReference<PagedResponse<Beneficiary>>() {}
        );

        testContext.setResponse(response);
        testContext.setPagedResponse(response.getBody());
    }

    @When("I search for beneficiaries with customerId {string} and type {string}")
    public void iSearchForBeneficiariesWithCustomerIdAndType(String customerId, String type) {
        String url = UriComponentsBuilder.fromPath("/api/v1/beneficiaries/search")
                .queryParam("customerId", customerId)
                .queryParam("beneficiaryType", type)
                .toUriString();

        ResponseEntity<PagedResponse<Beneficiary>> response = restTemplate.exchange(
                url,
                HttpMethod.GET,
                null,
                new ParameterizedTypeReference<PagedResponse<Beneficiary>>() {}
        );

        testContext.setResponse(response);
        testContext.setPagedResponse(response.getBody());
    }

    @When("I search for beneficiaries with customerId {string} and status {string}")
    public void iSearchForBeneficiariesWithCustomerIdAndStatus(String customerId, String status) {
        String url = UriComponentsBuilder.fromPath("/api/v1/beneficiaries/search")
                .queryParam("customerId", customerId)
                .queryParam("status", status)
                .toUriString();

        ResponseEntity<PagedResponse<Beneficiary>> response = restTemplate.exchange(
                url,
                HttpMethod.GET,
                null,
                new ParameterizedTypeReference<PagedResponse<Beneficiary>>() {}
        );

        testContext.setResponse(response);
        testContext.setPagedResponse(response.getBody());
    }

    @When("I search for beneficiaries with customerId {string} and bankCode {string}")
    public void iSearchForBeneficiariesWithCustomerIdAndBankCode(String customerId, String bankCode) {
        String url = UriComponentsBuilder.fromPath("/api/v1/beneficiaries/search")
                .queryParam("customerId", customerId)
                .queryParam("beneficiaryBankCode", bankCode)
                .toUriString();

        ResponseEntity<PagedResponse<Beneficiary>> response = restTemplate.exchange(
                url,
                HttpMethod.GET,
                null,
                new ParameterizedTypeReference<PagedResponse<Beneficiary>>() {}
        );

        testContext.setResponse(response);
        testContext.setPagedResponse(response.getBody());
    }

    @When("I search for beneficiaries with customerId {string} with page {int} and size {int}")
    public void iSearchForBeneficiariesWithPagination(String customerId, int page, int size) {
        String url = UriComponentsBuilder.fromPath("/api/v1/beneficiaries/search")
                .queryParam("customerId", customerId)
                .queryParam("page", page)
                .queryParam("size", size)
                .toUriString();

        ResponseEntity<PagedResponse<Beneficiary>> response = restTemplate.exchange(
                url,
                HttpMethod.GET,
                null,
                new ParameterizedTypeReference<PagedResponse<Beneficiary>>() {}
        );

        testContext.setResponse(response);
        testContext.setPagedResponse(response.getBody());
    }

    @When("I search for beneficiaries with customerId {string} sorted by {string} in {string} order")
    public void iSearchForBeneficiariesWithSorting(String customerId, String sortBy, String sortDirection) {
        String url = UriComponentsBuilder.fromPath("/api/v1/beneficiaries/search")
                .queryParam("customerId", customerId)
                .queryParam("sortBy", sortBy)
                .queryParam("sortDirection", sortDirection)
                .toUriString();

        ResponseEntity<PagedResponse<Beneficiary>> response = restTemplate.exchange(
                url,
                HttpMethod.GET,
                null,
                new ParameterizedTypeReference<PagedResponse<Beneficiary>>() {}
        );

        testContext.setResponse(response);
        testContext.setPagedResponse(response.getBody());
    }

    @When("I search for beneficiaries with the following criteria:")
    public void iSearchForBeneficiariesWithCriteria(Map<String, String> criteria) {
        UriComponentsBuilder builder = UriComponentsBuilder.fromPath("/api/v1/beneficiaries/search");
        
        criteria.forEach(builder::queryParam);

        ResponseEntity<PagedResponse<Beneficiary>> response = restTemplate.exchange(
                builder.toUriString(),
                HttpMethod.GET,
                null,
                new ParameterizedTypeReference<PagedResponse<Beneficiary>>() {}
        );

        testContext.setResponse(response);
        testContext.setPagedResponse(response.getBody());
    }

    @Then("the search should return {int} beneficiaries")
    public void theSearchShouldReturnBeneficiaries(int expectedCount) {
        PagedResponse<Beneficiary> pagedResponse = testContext.getPagedResponse();
        assertThat(pagedResponse).isNotNull();
        assertThat(pagedResponse.getContent()).hasSize(expectedCount);
    }

    @Then("all beneficiaries should belong to customer {string}")
    public void allBeneficiariesShouldBelongToCustomer(String customerId) {
        PagedResponse<Beneficiary> pagedResponse = testContext.getPagedResponse();
        assertThat(pagedResponse).isNotNull();
        assertThat(pagedResponse.getContent())
                .allMatch(b -> customerId.equals(b.getCustomerId()));
    }

    @Then("the first beneficiary should have name {string}")
    public void theFirstBeneficiaryShouldHaveName(String expectedName) {
        PagedResponse<Beneficiary> pagedResponse = testContext.getPagedResponse();
        assertThat(pagedResponse).isNotNull();
        assertThat(pagedResponse.getContent()).isNotEmpty();
        assertThat(pagedResponse.getContent().get(0).getBeneficiaryName()).isEqualTo(expectedName);
    }

    @Then("all beneficiaries should have type {string}")
    public void allBeneficiariesShouldHaveType(String expectedType) {
        PagedResponse<Beneficiary> pagedResponse = testContext.getPagedResponse();
        assertThat(pagedResponse).isNotNull();
        assertThat(pagedResponse.getContent())
                .allMatch(b -> expectedType.equals(b.getBeneficiaryType()));
    }

    @Then("all beneficiaries should have status {string}")
    public void allBeneficiariesShouldHaveStatus(String expectedStatus) {
        PagedResponse<Beneficiary> pagedResponse = testContext.getPagedResponse();
        assertThat(pagedResponse).isNotNull();
        assertThat(pagedResponse.getContent())
                .allMatch(b -> expectedStatus.equals(b.getStatus()));
    }

    @Then("all beneficiaries should have bankCode {string}")
    public void allBeneficiariesShouldHaveBankCode(String expectedBankCode) {
        PagedResponse<Beneficiary> pagedResponse = testContext.getPagedResponse();
        assertThat(pagedResponse).isNotNull();
        assertThat(pagedResponse.getContent())
                .allMatch(b -> expectedBankCode.equals(b.getBeneficiaryBankCode()));
    }

    @Then("the page number should be {int}")
    public void thePageNumberShouldBe(int expectedPage) {
        PagedResponse<Beneficiary> pagedResponse = testContext.getPagedResponse();
        assertThat(pagedResponse).isNotNull();
        assertThat(pagedResponse.getPage()).isEqualTo(expectedPage);
    }

    @Then("the total elements should be {int}")
    public void theTotalElementsShouldBe(int expectedTotal) {
        PagedResponse<Beneficiary> pagedResponse = testContext.getPagedResponse();
        assertThat(pagedResponse).isNotNull();
        assertThat(pagedResponse.getTotalElements()).isEqualTo(expectedTotal);
    }

    @Then("the total pages should be {int}")
    public void theTotalPagesShouldBe(int expectedPages) {
        PagedResponse<Beneficiary> pagedResponse = testContext.getPagedResponse();
        assertThat(pagedResponse).isNotNull();
        assertThat(pagedResponse.getTotalPages()).isEqualTo(expectedPages);
    }

    @Then("the beneficiaries should be sorted by name in ascending order")
    public void theBeneficiariesShouldBeSortedByNameInAscendingOrder() {
        PagedResponse<Beneficiary> pagedResponse = testContext.getPagedResponse();
        assertThat(pagedResponse).isNotNull();
        List<Beneficiary> beneficiaries = pagedResponse.getContent();
        
        for (int i = 0; i < beneficiaries.size() - 1; i++) {
            String name1 = beneficiaries.get(i).getBeneficiaryName();
            String name2 = beneficiaries.get(i + 1).getBeneficiaryName();
            assertThat(name1.compareTo(name2)).isLessThanOrEqualTo(0);
        }
    }
}
