# Generated by GitHub Copilot Agent
# Issue: #0
# Date: 2025-12-18
# NOTE: This test was auto-generated. Review and modify as needed.

Feature: Beneficiary Analytics
  As a customer
  I want to get analytics on my beneficiaries
  So that I can understand my payment patterns and compliance

  Background:
    Given the beneficiary service is available

  Scenario: Get customer beneficiary analytics
    Given the following beneficiaries exist for customer "CUST_ANALYTICS_001":
      | beneficiaryName | beneficiaryType  | status   | beneficiaryBankName |
      | Alice Alpha     | DOMESTIC        | ACTIVE   | Bank A             |
      | Bob Beta        | INTERNATIONAL   | ACTIVE   | Bank B             |
      | Charlie Gamma   | DOMESTIC        | INACTIVE | Bank A             |
      | Diana Delta     | DOMESTIC        | ACTIVE   | Bank C             |
    When I request analytics for customer "CUST_ANALYTICS_001"
    Then the analytics should show total beneficiaries as 4
    And the analytics should show active beneficiaries as 3
    And the analytics should show inactive beneficiaries as 1
    And the analytics should show 3 DOMESTIC beneficiaries
    And the analytics should show 1 INTERNATIONAL beneficiaries
    And the analytics should show 2 beneficiaries for "Bank A"

  Scenario: Get analytics for customer with no beneficiaries
    When I request analytics for customer "CUST_NO_BENEFICIARIES"
    Then the analytics should show total beneficiaries as 0
    And the analytics should show active beneficiaries as 0
    And the analytics should show inactive beneficiaries as 0

  Scenario: Find potential duplicate beneficiaries
    Given the following beneficiaries exist for customer "CUST_DUPLICATES_001":
      | beneficiaryName | beneficiaryAccountNumber |
      | John Doe        | ACC_001                 |
      | JohnDoe         | ACC_002                 |
      | Jane Smith      | ACC_003                 |
    When I check for potential duplicates for customer "CUST_DUPLICATES_001"
    Then the duplicate check should find 1 or more potential duplicates
    And the duplicates should include "John Doe" and "JohnDoe"

  Scenario: No duplicates found
    Given the following beneficiaries exist for customer "CUST_NO_DUPLICATES_001":
      | beneficiaryName | beneficiaryAccountNumber |
      | Alice Anderson  | ACC_001                 |
      | Zara Zhang      | ACC_002                 |
    When I check for potential duplicates for customer "CUST_NO_DUPLICATES_001"
    Then the duplicate check should find 0 potential duplicates

  Scenario: Get beneficiary usage report
    Given the following beneficiaries exist for customer "CUST_USAGE_001" created in the last 30 days:
      | beneficiaryName | daysAgo |
      | Alice Alpha     | 25      |
      | Bob Beta        | 15      |
      | Charlie Gamma   | 5       |
    When I request a usage report for customer "CUST_USAGE_001" for the last 30 days
    Then the usage report should show total beneficiaries as 3
    And the usage report should show 3 beneficiaries added in the period
    And the usage report should show growth rate as 100.0 percent

  Scenario: Get usage report for specific time period
    Given the following beneficiaries exist for customer "CUST_PERIOD_001":
      | beneficiaryName | daysAgo |
      | Old Beneficiary | 60      |
      | Recent One      | 5       |
      | Recent Two      | 3       |
    When I request a usage report for customer "CUST_PERIOD_001" for the last 7 days
    Then the usage report should show total beneficiaries as 3
    And the usage report should show 2 beneficiaries added in the period
