# Generated by GitHub Copilot Agent
# Issue: #<issue-number>
# Date: 2025-12-15
# DO NOT EDIT: This test was auto-generated. Review and modify as needed.

Feature: Beneficiary Validation
  As a customer
  I want beneficiaries to be validated before creation
  So that only valid beneficiaries are added to my account

  Background:
    Given the beneficiary service is available

  Scenario: Reject beneficiary with invalid account number format
    When I create a beneficiary with invalid account number "ABC"
    Then the response status should be 400
    And the error message should contain "Invalid account number format"

  Scenario: Reject beneficiary with invalid bank code format
    When I create a beneficiary with invalid bank code "123"
    Then the response status should be 400
    And the error message should contain "Invalid bank code format"

  Scenario: Reject beneficiary with empty name
    When I create a beneficiary with empty beneficiary name
    Then the response status should be 400
    And the error message should contain "Beneficiary name is required"

  Scenario: Reject beneficiary with too short name
    When I create a beneficiary with name "A"
    Then the response status should be 400
    And the error message should contain "Beneficiary name must be at least 2 characters"

  Scenario: Reject beneficiary on sanctions list
    When I create a beneficiary that is sanctioned
    Then the response status should be 400
    And the error message should contain "sanctions list"

  Scenario: Accept beneficiary with valid account number (8 digits)
    When I create a beneficiary with account number "12345678"
    Then the beneficiary should be created successfully
    And the response status should be 201

  Scenario: Accept beneficiary with valid account number (20 digits)
    When I create a beneficiary with account number "12345678901234567890"
    Then the beneficiary should be created successfully
    And the response status should be 201

  Scenario: Accept beneficiary with valid bank code (6 characters)
    When I create a beneficiary with bank code "BANK01"
    Then the beneficiary should be created successfully
    And the response status should be 201

  Scenario: Accept beneficiary with valid bank code (11 characters)
    When I create a beneficiary with bank code "BANKCODE123"
    Then the beneficiary should be created successfully
    And the response status should be 201

  Scenario: Warn about high fraud score but allow in non-strict mode
    When I create a beneficiary with high fraud score
    Then the beneficiary should be created successfully
    And the response status should be 201
    And a warning should be logged about fraud score

  Scenario: Reject beneficiary with high fraud score in strict mode
    Given strict validation mode is enabled
    When I create a beneficiary with high fraud score
    Then the response status should be 400
    And the error message should contain "High fraud risk detected"

  Scenario: Reject beneficiary with inactive account status
    When I create a beneficiary with inactive account
    Then the response status should be 400
    And the error message should contain "account is not active"

  Scenario: Accept beneficiary with active account status
    When I create a beneficiary with active account
    Then the beneficiary should be created successfully
    And the response status should be 201

  Scenario: Handle third-party validation service timeout in non-strict mode
    When I create a beneficiary and validation service times out
    Then the beneficiary should be created successfully
    And the response status should be 201
    And a warning should be logged about validation failure

  Scenario: Reject beneficiary when third-party validation service fails in strict mode
    Given strict validation mode is enabled
    When I create a beneficiary and validation service times out
    Then the response status should be 400
    And the error message should contain "Unable to validate beneficiary"
