# Generated by GitHub Copilot Agent
# Issue: #generate-tests-for-branch-main
# Date: 2025-12-18
# DO NOT EDIT: This test was auto-generated. Review and modify as needed.

Feature: Beneficiary Analytics
  As a customer
  I want to view analytics about my beneficiaries
  So that I can understand my beneficiary management patterns

  Background:
    Given the beneficiary service is available

  Scenario: Get customer beneficiary analytics
    Given I have beneficiaries for customer "CUST001"
    When I request analytics for customer "CUST001"
    Then the analytics should include total beneficiaries count
    And the analytics should include active beneficiaries count
    And the analytics should include inactive beneficiaries count
    And the analytics should include beneficiaries grouped by type
    And the analytics should include beneficiaries grouped by bank

  Scenario: Get analytics with most recent beneficiary information
    Given I have beneficiaries for customer "CUST002"
    When I request analytics for customer "CUST002"
    Then the analytics should include most recent beneficiary name
    And the analytics should include most recent added date

  Scenario: Get analytics for customer with no beneficiaries
    When I request analytics for customer "CUST_NO_DATA"
    Then the analytics should show zero total beneficiaries
    And the analytics should show zero active beneficiaries

  Scenario: Find potential duplicate beneficiaries
    Given I have beneficiaries for customer "CUST001"
    When I request potential duplicates for customer "CUST001"
    Then the duplicate search should complete successfully

  Scenario: Get beneficiary usage report
    Given I have beneficiaries for customer "CUST001"
    When I request usage report for customer "CUST001" for the last 30 days
    Then the report should include total beneficiaries
    And the report should include beneficiaries added in period
    And the report should include growth rate percentage
    And the report should include report period dates

  Scenario: Get usage report with most active day
    Given I have beneficiaries for customer "CUST002"
    When I request usage report for customer "CUST002" for the last 365 days
    Then the report should include total beneficiaries
    And the report should include beneficiaries added in period

  Scenario: Get analytics grouped by beneficiary type
    Given I have beneficiaries for customer "CUST003"
    When I request analytics for customer "CUST003"
    Then the analytics should include beneficiaries grouped by type
    And the type breakdown should contain valid beneficiary types

  Scenario: Get analytics grouped by bank
    Given I have beneficiaries for customer "CUST002"
    When I request analytics for customer "CUST002"
    Then the analytics should include beneficiaries grouped by bank
    And the bank breakdown should contain bank names
