# Generated by GitHub Copilot Agent
# Issue: #0
# Date: 2025-12-18
# NOTE: This test was auto-generated. Review and modify as needed.

Feature: Search Beneficiaries
  As a customer
  I want to search for beneficiaries using various criteria
  So that I can find specific beneficiaries quickly

  Background:
    Given the beneficiary service is available
    And the following beneficiaries exist:
      | customerId | beneficiaryName | beneficiaryType  | status   | beneficiaryBankCode |
      | CUST_SEARCH_001 | Alice Alpha    | DOMESTIC        | ACTIVE   | BANK_001           |
      | CUST_SEARCH_001 | Bob Beta       | INTERNATIONAL   | ACTIVE   | BANK_002           |
      | CUST_SEARCH_001 | Charlie Gamma  | DOMESTIC        | INACTIVE | BANK_001           |
      | CUST_SEARCH_001 | Diana Delta    | INTERNATIONAL   | ACTIVE   | BANK_003           |

  Scenario: Search beneficiaries by customer ID
    When I search for beneficiaries with customerId "CUST_SEARCH_001"
    Then the search should return 4 beneficiaries
    And all beneficiaries should belong to customer "CUST_SEARCH_001"

  Scenario: Search beneficiaries by name
    When I search for beneficiaries with customerId "CUST_SEARCH_001" and name "Alice"
    Then the search should return 1 beneficiaries
    And the first beneficiary should have name "Alice Alpha"

  Scenario: Search beneficiaries by type
    When I search for beneficiaries with customerId "CUST_SEARCH_001" and type "DOMESTIC"
    Then the search should return 2 beneficiaries
    And all beneficiaries should have type "DOMESTIC"

  Scenario: Search beneficiaries by status
    When I search for beneficiaries with customerId "CUST_SEARCH_001" and status "ACTIVE"
    Then the search should return 3 beneficiaries
    And all beneficiaries should have status "ACTIVE"

  Scenario: Search beneficiaries by bank code
    When I search for beneficiaries with customerId "CUST_SEARCH_001" and bankCode "BANK_001"
    Then the search should return 2 beneficiaries
    And all beneficiaries should have bankCode "BANK_001"

  Scenario: Search beneficiaries with pagination
    When I search for beneficiaries with customerId "CUST_SEARCH_001" with page 0 and size 2
    Then the search should return 2 beneficiaries
    And the page number should be 0
    And the total elements should be 4
    And the total pages should be 2

  Scenario: Search beneficiaries with sorting
    When I search for beneficiaries with customerId "CUST_SEARCH_001" sorted by "beneficiaryName" in "ASC" order
    Then the search should return 4 beneficiaries
    And the beneficiaries should be sorted by name in ascending order

  Scenario: Search with multiple filters
    When I search for beneficiaries with the following criteria:
      | customerId | CUST_SEARCH_001 |
      | type       | DOMESTIC        |
      | status     | ACTIVE          |
    Then the search should return 1 beneficiaries
    And the first beneficiary should have name "Alice Alpha"

  Scenario: Search with no results
    When I search for beneficiaries with customerId "NON_EXISTENT_CUSTOMER"
    Then the search should return 0 beneficiaries
    And the total elements should be 0
