# Generated by GitHub Copilot Agent
# Issue: #generate-tests-for-branch-main
# Date: 2025-12-18
# DO NOT EDIT: This test was auto-generated. Review and modify as needed.

Feature: Search Beneficiaries
  As a customer
  I want to search for beneficiaries with various filters
  So that I can find specific beneficiaries quickly

  Background:
    Given the beneficiary service is available

  Scenario: Search beneficiaries by customer ID
    Given I have beneficiaries for customer "CUST001"
    When I search for beneficiaries with customerId "CUST001"
    Then the search should return beneficiaries
    And all beneficiaries should belong to customer "CUST001"

  Scenario: Search beneficiaries by name
    When I search for beneficiaries with name containing "Old"
    Then the search should return beneficiaries
    And all beneficiaries should have name containing "Old"

  Scenario: Search beneficiaries by type
    When I search for beneficiaries with type "DOMESTIC"
    Then the search should return beneficiaries
    And all beneficiaries should be of type "DOMESTIC"

  Scenario: Search beneficiaries by status
    When I search for beneficiaries with status "ACTIVE"
    Then the search should return beneficiaries
    And all beneficiaries should have status "ACTIVE"

  Scenario: Search beneficiaries with pagination
    Given I have beneficiaries for customer "CUST002"
    When I search for beneficiaries with customerId "CUST002" page 0 and size 2
    Then the search should return 2 beneficiaries
    And the page should be 0
    And the result should indicate it is the first page

  Scenario: Search beneficiaries sorted by name ascending
    Given I have beneficiaries for customer "CUST002"
    When I search for beneficiaries with customerId "CUST002" sorted by "beneficiaryName" in "ASC" order
    Then the search should return beneficiaries
    And the beneficiaries should be sorted by name in ascending order

  Scenario: Search beneficiaries with multiple filters
    When I search for beneficiaries with customerId "CUST003" and type "DOMESTIC"
    Then the search should return beneficiaries
    And all beneficiaries should belong to customer "CUST003"
    And all beneficiaries should be of type "DOMESTIC"

  Scenario: Search with no matching results
    When I search for beneficiaries with customerId "NONEXISTENT"
    Then the search should return empty results
    And the total count should be 0

  Scenario: Search beneficiaries by bank code
    When I search for beneficiaries with bankCode "BANKCODE1"
    Then the search should return beneficiaries
    And all beneficiaries should have bankCode "BANKCODE1"

  Scenario: Search beneficiaries within date range
    When I search for beneficiaries created in the last 365 days
    Then the search should return beneficiaries
    And all beneficiaries should be created within the date range
